# Copyright 2026 Xuebin Feng
# Author affiliation: University of Toronto
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
File: Align_Similarity_Matrix.py
===================================
Description:
This script computes an all-vs-all sequence similarity matrix utilizing protein embeddings instead of traditional sequence 
characters. It performs alignment scoring using dynamic programming on distance matrices derived from the embeddings.

Input:
- HDF5 dataset containing sequence embeddings generated by models like ESM (`{SEQUENCE_SET}_{MODEL_NAME}_embeddings.h5`).

Output:
- A network edge HDF5 file containing pairwise combinations (i, j), raw local/global scores, and alignment lengths (`{SEQUENCE_SET}_{MODEL_NAME}_network.h5`).

Settings:
- SEQUENCE_SET: The base name of the project.
- MODEL_NAME: The name of the embedding model used.
- BATCH_SIZE: Number of pairs to process before writing to disk (prevents memory overflow).
- WORKERS: Number of multiprocessing workers to use.
- HOST_CACHE_GB: Automatic or explicit host-RAM cap for packed embeddings.
- EXECUTION_MODE: Automatic, scalar, or tiled pairwise score execution.
- ACCELERATOR_PRECISION: Validated automatic, IEEE FP32, or TF32 CUDA matmul.
- LOCAL_GAP_P: The gap penalty for local alignment (e.g. Smith-Waterman style).
- GLOBAL_GAP_P: The gap penalty for global alignment (e.g. Needleman-Wunsch style).

Algorithm:
1. Packs the embedding database in bounded host RAM when possible; otherwise
   loads byte-bounded sequence tiles from HDF5.
2. Benchmarks each eligible device, execution variant, and lane setup once on
   globally representative, cost-matched warm-up and timed pair halves.
3. Passes those matrices by reference through a bounded queue to parallel CPU
   threads, which evaluate Global and Local Alignments using Numba functions
   compiled to release the Python GIL.
4. On CPU-only systems, distributes complete pairs across the CPU workers.
5. Streams intermediate results into atomic HDF5 batches and merges them into
   the final datasets.
"""
# %% Import Necessary Libraries
# Limit threads to prevent CPU thrashing
import os
try:
    from tools import _bootstrap
except ModuleNotFoundError:
    import _bootstrap
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

import pickle
import numpy as np
import torch
import math
import glob
import shutil
import sys
import h5py
import hashlib
import threading
import time
from collections import deque
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from contextlib import nullcontext
from multiprocessing import Pool, set_start_method
from tqdm import tqdm
from utilities import Hardware_Utils
from utilities.Embedding_Alignment_Engine import (
    BenchmarkPhaseTimer,
    EmbeddingTileStore,
    compare_precision_results,
    cuda_matmul_precision,
    cuda_memory_plan,
    evenly_spaced_task_subset,
    estimate_cuda_working_set,
    get_accelerator_backend,
    matched_benchmark_task_halves,
    normalize_execution_mode,
    normalize_precision_setting,
    run_tiled_accelerator_pipeline,
    run_tiled_cuda_pipeline,
    tiled_accelerator_support,
)
from utilities.Alignment_Score_Kernels import global_local_scores
from utilities.Embedding_HDF5 import read_embedding_manifest

# ==========================================
# CONFIGURATION
# ==========================================
INPUT_HDF5 = None
EDGE_PREFILTERING = False
PREFILTER_STRENGTH = 20
POOLING_METHOD = "max"    # ("mean", "max") - method to pool residue embeddings into sequence vectors
LENGTH_RATIO_POWER = 2.0  # (float) - exponent to scale the sequence length ratio penalty
WORKERS = 12
DEVICE_SELECTION = "auto"
EXECUTION_MODE = "auto"
ACCELERATOR_BENCHMARK_HALF_PAIRS = 4096
CPU_BENCHMARK_HALF_PAIRS = 256
PRECISION_VALIDATION_PAIRS = 2048
# Legacy saved-setting aliases. When supplied, these override the corresponding
# new half-size settings without preserving the former two-stage execution.
ACCELERATOR_TUNE_PAIRS = None
ACCELERATOR_CONFIRM_PAIRS = None
HOST_CACHE_GB = "auto"
ACCELERATOR_PRECISION = "auto"
# Compatibility for callers that use _accelerator_worker_count directly.
# Production scheduling always uses the automatic lane tuner.
GPU_STREAMS = 4
LOCAL_GAP_P = -2.0
GLOBAL_GAP_P = 0.0
BATCH_SIZE = 500000

from utilities.Tool_Directories import project_directory_defaults
from utilities.Tool_Settings import inherited_settings_path, load_tool_settings

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
_DEFAULT_DIRECTORIES = project_directory_defaults(PROJECT_ROOT)
EMBED_DIR = _DEFAULT_DIRECTORIES["EMBED_DIR"]
NETWORK_DIR = _DEFAULT_DIRECTORIES["NETWORK_DIR"]

# --- JSON Settings Override ---
import json
import ast
import os

# Automatically calculate the root directory of the SSN project for the current PC
# (Tool scripts are located in the /tools/ folder)
SETTINGS_FILE = inherited_settings_path(__file__) or os.path.join(PROJECT_ROOT, "tools_settings.json")

if __name__ != "__main__" and os.path.exists(SETTINGS_FILE):
    try:
        with open(SETTINGS_FILE, "r", encoding="utf-8") as f:
            all_settings = json.load(f)
            
            # 1. Load GLOBAL directories and convert relative paths to absolute paths
            if "DIRECTORIES" in all_settings:
                for k, v in all_settings["DIRECTORIES"].items():
                    if k in globals() and v is not None and str(v).strip() != "":
                        # Expand relative paths dynamically based on the current PC
                        if not os.path.isabs(str(v)):
                            v = os.path.normpath(os.path.join(PROJECT_ROOT, str(v)))
                        globals()[k] = v
                        
            # 2. Load script-specific settings
            script_name = os.path.basename(__file__)
            if script_name in all_settings:
                user_settings = all_settings[script_name]
                for k, v in user_settings.items():
                    if k in globals() and v is not None and str(v).strip() != "":
                        orig = globals()[k]
                        
                        # Type casting to match the original Python variable type
                        if isinstance(orig, int) and not isinstance(orig, bool):
                            try: v = int(v)
                            except: pass
                        elif isinstance(orig, float):
                            try: v = float(v)
                            except: pass
                        elif isinstance(orig, list):
                            try: v = ast.literal_eval(v) if isinstance(v, str) else v
                            except: pass
                        elif orig is None:
                            if v == "None": v = None
                            elif str(v).replace('.', '', 1).isdigit():
                                v = float(v) if '.' in str(v) else int(v)
                                
                        # Convert any script-specific directory paths to absolute paths
                        if isinstance(v, str) and k.endswith("_DIR") and not os.path.isabs(v):
                            v = os.path.normpath(os.path.join(PROJECT_ROOT, v))
                            
                        globals()[k] = v
    except Exception as e:
        print(f"Failed to load user settings: {e}")

import re
MODEL_NAME = "unknown"
SEQUENCE_SET = ""
FULL_INPUT_HDF5 = None
RESULTS_DIR = None
FINAL_OUTPUT_NET = None
active_matmul_precision = "ieee_fp32"
active_embedding_store = None
active_sequence_lengths = None


def _benchmark_half_sizes():
    accelerator_half = (
        ACCELERATOR_BENCHMARK_HALF_PAIRS
        if ACCELERATOR_CONFIRM_PAIRS is None
        else ACCELERATOR_CONFIRM_PAIRS
    )
    cpu_half = (
        CPU_BENCHMARK_HALF_PAIRS
        if ACCELERATOR_TUNE_PAIRS is None
        else ACCELERATOR_TUNE_PAIRS
    )
    return max(1, int(accelerator_half)), max(1, int(cpu_half))


def configure_runtime_paths():
    """Resolve GUI-selected paths immediately before starting the job."""
    global MODEL_NAME, SEQUENCE_SET
    global FULL_INPUT_HDF5, RESULTS_DIR, FINAL_OUTPUT_NET

    if INPUT_HDF5 is None or not str(INPUT_HDF5).strip():
        raise ValueError("No embeddings file has been selected.")

    selected_path = os.fspath(INPUT_HDF5)
    filename = os.path.basename(selected_path)
    base_name = filename.replace("_embeddings.h5", "").replace(".h5", "")

    MODEL_NAME = "unknown"
    SEQUENCE_SET = base_name
    match = re.search(r"^(.*)_\[(.*)\]_embeddings\.h5$", filename)
    if match:
        SEQUENCE_SET = match.group(1)
        MODEL_NAME = match.group(2)

    FULL_INPUT_HDF5 = (
        os.path.normpath(selected_path)
        if os.path.isabs(selected_path)
        else os.path.normpath(os.path.join(EMBED_DIR, selected_path))
    )
    RESULTS_DIR = os.path.join(
        NETWORK_DIR,
        f"{SEQUENCE_SET}_[{MODEL_NAME}]_network_temp",
    )
    FINAL_OUTPUT_NET = os.path.join(
        NETWORK_DIR,
        f"{SEQUENCE_SET}_[{MODEL_NAME}]_network.h5",
    )
        
# %% =======================================
# KERNELS
# ==========================================
def calculate_file_hash(file_path):
    """
    Computes the MD5 checksum of a file in chunks to verify consistency.
    """
    hasher = hashlib.md5()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


class EmbeddingFileError(RuntimeError):
    """Raised when an embedding HDF5 file is incomplete or incompatible."""


def load_embedding_metadata(file_path):
    """
    Validate an embedding database using Embedding_HDF5.read_embedding_manifest
    and return ordered headers, safe headers, and sequence lengths.
    """
    try:
        with h5py.File(file_path, "r") as hf:
            manifest = read_embedding_manifest(
                hf,
                require_complete=True,
                validate_embeddings=True,
            )
            headers = manifest.headers
            safe_headers = [
                header.replace("/", "_").replace("\\", "_")
                for header in headers
            ]
            seq_lens = [len(seq) for seq in manifest.sequences]
    except EmbeddingFileError:
        raise
    except Exception as error:
        raise EmbeddingFileError(
            f"Embedding file '{file_path}' validation failed: {error}"
        ) from error

    return headers, safe_headers, seq_lens, manifest


def _device_cache_key(device):
    """Return a stable key for per-backend scoring capability caches."""
    return (_device_type(device), getattr(device, "index", None))


def _normalize_embedding_torch(embedding, device):
    """Transfer one embedding to ``device`` and L2-normalize its residues."""
    tensor = torch.as_tensor(embedding, device=device, dtype=torch.float32)
    return torch.nn.functional.normalize(tensor, p=2, dim=-1)


def _normalized_row_for_active_lane(emb_i, device):
    """
    Return the normalized left embedding for the active accelerator lane.

    ``_compute_accelerated_matrix`` supplies a row key while it owns the lane.
    The cached tensor therefore remains on the same worker thread and stream
    that created it. Direct callers, including the CPU-only process fallback,
    do not have an active row key and retain the original per-pair behavior.
    """
    active_row_key = getattr(accelerator_thread_state, "active_row_key", None)
    if active_row_key is None:
        return _normalize_embedding_torch(emb_i, device)

    cached_row_key = getattr(accelerator_thread_state, "normalized_row_key", None)
    if cached_row_key != active_row_key:
        accelerator_thread_state.normalized_row = _normalize_embedding_torch(
            emb_i,
            device,
        )
        accelerator_thread_state.normalized_row_key = active_row_key
    return accelerator_thread_state.normalized_row


std_mean_support_cache = {}


def _score_matrix_statistics(sim_mat, device):
    """Return row/column means and standard deviations with safe fallback."""
    cache_key = _device_cache_key(device)
    fused_supported = std_mean_support_cache.get(cache_key)

    if fused_supported is not False:
        try:
            row_std, row_mean = torch.std_mean(
                sim_mat,
                dim=1,
                keepdim=True,
                correction=0,
            )
            col_std, col_mean = torch.std_mean(
                sim_mat,
                dim=0,
                keepdim=True,
                correction=0,
            )
        except (RuntimeError, NotImplementedError):
            # Some accelerator integrations do not implement std_mean. Only
            # remember the failure after the established operations succeed,
            # so unrelated failures are not silently cached as capabilities.
            row_mean = sim_mat.mean(dim=1, keepdim=True)
            row_std = sim_mat.std(dim=1, keepdim=True, correction=0)
            col_mean = sim_mat.mean(dim=0, keepdim=True)
            col_std = sim_mat.std(dim=0, keepdim=True, correction=0)
            std_mean_support_cache[cache_key] = False
        else:
            if fused_supported is None:
                std_mean_support_cache[cache_key] = True
    else:
        row_mean = sim_mat.mean(dim=1, keepdim=True)
        row_std = sim_mat.std(dim=1, keepdim=True, correction=0)
        col_mean = sim_mat.mean(dim=0, keepdim=True)
        col_std = sim_mat.std(dim=0, keepdim=True, correction=0)

    return row_mean, row_std, col_mean, col_std


def _score_matrix_from_normalized_row(t_i_norm, emb_j, device):
    """Calculate a score matrix when the left embedding is pre-normalized."""
    t_j_norm = _normalize_embedding_torch(emb_j, device)
    cos_sim = torch.mm(t_i_norm, t_j_norm.T).clamp(-1.0, 1.0)
    dist_mat = 1.0 - cos_sim
    sim_mat = torch.exp(-dist_mat)

    epsilon = 1e-8
    row_mean, row_std, col_mean, col_std = _score_matrix_statistics(
        sim_mat,
        device,
    )

    z_r = (sim_mat - row_mean) / (row_std + epsilon)
    z_c = (sim_mat - col_mean) / (col_std + epsilon)
    final_score = (z_r + z_c) / 2.0

    return final_score.to(dtype=torch.float32, device="cpu").numpy()


def compute_score_matrix_torch(emb_i, emb_j, device):
    t_i_norm = _normalized_row_for_active_lane(emb_i, device)
    return _score_matrix_from_normalized_row(t_i_norm, emb_j, device)

# %% =======================================
# HDF5 WORKER INITIALIZATION
# ==========================================
worker_hf = None
worker_device = None

def init_worker(h5_path):
    global worker_hf, worker_device
    worker_hf = h5py.File(h5_path, "r", libver='latest', swmr=True)
    # This initializer is used only by the CPU-only fallback. Keeping the
    # device explicit prevents child processes from creating GPU contexts.
    worker_device = torch.device("cpu")

# %% =======================================
# CPU ALIGNMENT WORKERS
# ==========================================
def calculate_alignment_data(args):
    """
    Run the dynamic-programming portion of one pair entirely on the CPU.

    The score matrix is produced by the single accelerator-owning thread and
    passed by reference to a CPU worker thread. The Numba kernels release the
    GIL, so multiple alignments can execute on separate CPU cores.
    """
    idx_i, idx_j, matrix = args

    g_raw, g_len, l_raw, l_len = global_local_scores(
        matrix,
        GLOBAL_GAP_P,
        LOCAL_GAP_P,
    )

    return (idx_i, idx_j, l_raw, l_len, g_raw, g_len)


def calculate_cpu_pair(args):
    """
    CPU-only fallback that computes both the score matrix and alignments.

    Multiple processes may execute this function because none of them creates
    or accesses an accelerator context.
    """
    idx_i, idx_j, header_i, header_j = args
    global worker_hf, worker_device

    emb_i = worker_hf["embeddings"][header_i][:]
    emb_j = worker_hf["embeddings"][header_j][:]
    matrix = compute_score_matrix_torch(emb_i, emb_j, worker_device)

    return calculate_alignment_data((idx_i, idx_j, matrix))


def _uses_accelerator(device):
    return getattr(device, "type", str(device).split(":", 1)[0]) != "cpu"


accelerator_thread_state = threading.local()
accelerator_lane_cache = {}


def _device_type(device):
    """Return a normalized PyTorch device type."""
    return getattr(device, "type", str(device).split(":", 1)[0])


def _supports_explicit_streams(device):
    """Return whether this backend exposes usable Python stream controls."""
    return _device_type(device) in {"cuda", "xpu"}


def _accelerator_worker_count(device, cpu_workers, requested_lanes=None):
    """
    Bound an explicit lane request to what the selected backend can use.

    ``requested_lanes`` is optional to preserve compatibility with callers of
    the previous CUDA-only helper.
    """
    if not _supports_explicit_streams(device):
        return 1
    if requested_lanes is None:
        requested_lanes = GPU_STREAMS
    return max(1, min(int(requested_lanes), int(cpu_workers)))


def _accelerator_lane_candidates(device, cpu_workers):
    """Return conservative tuning candidates for the active backend."""
    device_type = _device_type(device)
    max_lanes = max(1, int(cpu_workers))

    if device_type == "cuda":
        candidates = [1, 2, 4, 8, 16]
        backend_cap = 16
    elif device_type == "xpu":
        candidates = [1, 2, 4]
        backend_cap = 4
    else:
        return [1]

    limit = min(max_lanes, backend_cap)
    bounded = [count for count in candidates if count <= limit]
    if limit not in bounded:
        bounded.append(limit)
    return sorted(set(bounded))


def _accelerator_name(device):
    """Return a stable device label for tuning messages and cache keys."""
    device_type = _device_type(device)
    try:
        if device_type == "cuda":
            return torch.cuda.get_device_name(device)
        if device_type == "xpu":
            return torch.xpu.get_device_name(device)
        if device_type == "mps" and hasattr(torch.backends.mps, "get_name"):
            return torch.backends.mps.get_name()
    except (AttributeError, RuntimeError):
        pass
    return str(device)


def _stream_context(device):
    """
    Return a context for a stream owned by the current accelerator thread.

    CUDA and XPU use separate explicit streams. MPS and other
    backends deliberately retain their default execution queue.
    """
    device_type = _device_type(device)
    if device_type == "cuda":
        backend = torch.cuda
    elif device_type == "xpu":
        backend = torch.xpu
    else:
        return nullcontext()

    stream = getattr(accelerator_thread_state, "stream", None)
    stream_key = getattr(accelerator_thread_state, "stream_key", None)
    current_key = (device_type, str(device))
    if stream is None or stream_key != current_key:
        stream = backend.Stream(device=device)
        accelerator_thread_state.stream = stream
        accelerator_thread_state.stream_key = current_key

    return _DeviceStreamContext(backend, device, stream)


class _DeviceStreamContext:
    """Enter matching device and stream contexts for CUDA or XPU."""

    def __init__(self, backend, device, stream):
        self.device_context = backend.device(device)
        self.stream_context = backend.stream(stream)

    def __enter__(self):
        self.device_context.__enter__()
        try:
            return self.stream_context.__enter__()
        except BaseException:
            self.device_context.__exit__(*sys.exc_info())
            raise

    def __exit__(self, exc_type, exc_value, traceback):
        try:
            return self.stream_context.__exit__(
                exc_type,
                exc_value,
                traceback,
            )
        finally:
            self.device_context.__exit__(exc_type, exc_value, traceback)


def _compute_accelerated_matrix(args):
    """
    Compute one score matrix on a stream owned by the current worker thread.

    All threads share one accelerator process. CUDA and XPU threads own
    separate streams; backends without public stream controls use one lane.
    """
    idx_i, idx_j, emb_i, emb_j, device = args
    with torch.inference_mode():
        with _stream_context(device):
            previous_row_key = getattr(
                accelerator_thread_state,
                "active_row_key",
                None,
            )
            accelerator_thread_state.active_row_key = (
                _device_cache_key(device),
                idx_i,
            )
            try:
                matrix = compute_score_matrix_torch(emb_i, emb_j, device)
            finally:
                if previous_row_key is None:
                    try:
                        del accelerator_thread_state.active_row_key
                    except AttributeError:
                        pass
                else:
                    accelerator_thread_state.active_row_key = previous_row_key

    return idx_i, idx_j, matrix


def _run_scalar_accelerated_pipeline(
    batch_tasks,
    workers,
    input_h5,
    device,
    batch_id,
    accelerator_workers,
    show_progress,
    result_callback=None,
    result_chunk_size=65536,
    warmup_task_count=0,
    benchmark_timer=None,
):
    """
    Run one complete accelerator/CPU pipeline with a fixed lane count.

    GPU and CPU queues are independently bounded. Matrices stay in the same
    process and are passed by reference, avoiding serialization and extra CUDA
    contexts while allowing both stages to remain busy.
    """
    batch_tasks = list(batch_tasks)
    warmup_task_count = int(warmup_task_count)
    if benchmark_timer is not None and (
        warmup_task_count < 0 or warmup_task_count >= len(batch_tasks)
    ):
        raise ValueError("Benchmark warm-up count must leave a timed task.")
    results = []
    ready_limit = max(accelerator_workers, min(workers, 8))
    cached_row_header = None
    cached_row_embedding = None
    progress_context = (
        tqdm(
            total=len(batch_tasks),
            desc=(
                f"  Batch {batch_id} "
                f"({accelerator_workers} accelerator lane"
                f"{'s' if accelerator_workers != 1 else ''})"
            ),
            leave=False,
        )
        if show_progress
        else nullcontext(None)
    )

    with h5py.File(input_h5, "r", libver="latest", swmr=True) as hf, \
            ThreadPoolExecutor(
                max_workers=accelerator_workers,
                thread_name_prefix="alignment-gpu",
            ) as gpu_executor, \
            ThreadPoolExecutor(
                max_workers=workers,
                thread_name_prefix="alignment-cpu",
            ) as cpu_executor, \
            progress_context as progress:
        def run_phase(phase_tasks):
            nonlocal cached_row_header, cached_row_embedding
            gpu_pending = set()
            cpu_pending = set()
            ready_for_cpu = deque()
            task_iterator = iter(phase_tasks)
            tasks_exhausted = False
            while (
                not tasks_exhausted
                or gpu_pending
                or ready_for_cpu
                or cpu_pending
            ):
                while ready_for_cpu and len(cpu_pending) < workers:
                    cpu_pending.add(
                        cpu_executor.submit(
                            calculate_alignment_data,
                            ready_for_cpu.popleft(),
                        )
                    )

                while (
                    not tasks_exhausted
                    and len(gpu_pending) < accelerator_workers
                    and len(ready_for_cpu) + len(gpu_pending) < ready_limit
                ):
                    try:
                        idx_i, idx_j, header_i, header_j = next(task_iterator)
                    except StopIteration:
                        tasks_exhausted = True
                        break

                    if header_i != cached_row_header:
                        cached_row_embedding = hf["embeddings"][header_i][:]
                        cached_row_header = header_i
                    emb_j = hf["embeddings"][header_j][:]
                    gpu_pending.add(
                        gpu_executor.submit(
                            _compute_accelerated_matrix,
                            (
                                idx_i,
                                idx_j,
                                cached_row_embedding,
                                emb_j,
                                device,
                            ),
                        )
                    )

                completed_gpu = {
                    future for future in gpu_pending if future.done()
                }
                completed_cpu = {
                    future for future in cpu_pending if future.done()
                }
                if not completed_gpu and not completed_cpu:
                    all_pending = gpu_pending | cpu_pending
                    if not all_pending:
                        continue
                    completed, _ = wait(
                        all_pending,
                        return_when=FIRST_COMPLETED,
                    )
                    completed_gpu = completed & gpu_pending
                    completed_cpu = completed & cpu_pending

                for future in completed_gpu:
                    gpu_pending.remove(future)
                    ready_for_cpu.append(future.result())
                for future in completed_cpu:
                    cpu_pending.remove(future)
                    results.append(future.result())
                    if progress is not None:
                        progress.update(1)
                    if (
                        result_callback is not None
                        and len(results) >= int(result_chunk_size)
                    ):
                        result_callback(results)
                        results.clear()

        if benchmark_timer is None:
            run_phase(batch_tasks)
        else:
            if warmup_task_count:
                run_phase(batch_tasks[:warmup_task_count])
            benchmark_timer.start()
            run_phase(batch_tasks[warmup_task_count:])
            benchmark_timer.stop()

    if result_callback is not None and results:
        result_callback(results)
        results.clear()
    return results


def _run_accelerated_pipeline(
    batch_tasks,
    workers,
    input_h5,
    device,
    batch_id,
    accelerator_workers,
    show_progress,
    matmul_precision="ieee_fp32",
    result_callback=None,
    warmup_task_count=0,
    benchmark_timer=None,
):
    """Compatibility wrapper for the original per-pair accelerator path."""
    with cuda_matmul_precision(matmul_precision):
        return _run_scalar_accelerated_pipeline(
            batch_tasks,
            workers,
            input_h5,
            device,
            batch_id,
            accelerator_workers,
            show_progress,
            result_callback=result_callback,
            warmup_task_count=warmup_task_count,
            benchmark_timer=benchmark_timer,
        )


def _select_accelerator_lanes(
    batch_tasks,
    workers,
    input_h5,
    device,
    batch_id,
    matmul_precision=None,
):
    """
    Select accelerator concurrency using a representative benchmark.

    The benchmark includes HDF5 input, accelerator work, the device-to-host
    transfer, and CPU alignment. This optimizes completed-pair throughput
    rather than accelerator utilization alone.
    """
    candidates = _accelerator_lane_candidates(device, workers)
    if matmul_precision is None:
        matmul_precision = active_matmul_precision
    if len(candidates) == 1 or len(batch_tasks) < 2:
        return 1

    cache_key = (
        _device_type(device),
        _accelerator_name(device),
        int(workers),
    )
    if cache_key in accelerator_lane_cache:
        return accelerator_lane_cache[cache_key]

    half_count = min(_benchmark_half_sizes()[0], len(batch_tasks) // 2)
    if half_count < 1:
        return 1
    tuning_tasks = evenly_spaced_task_subset(batch_tasks, half_count * 2)
    device_name = cache_key[1]
    print(
        f"  > Auto-tuning accelerator lanes on {device_name} "
        f"using {half_count} warm-up + {half_count} timed pairs..."
    )

    measured_rates = {}
    for lanes in candidates:
        timer = BenchmarkPhaseTimer()
        try:
            _run_accelerated_pipeline(
                tuning_tasks,
                workers,
                input_h5,
                device,
                batch_id,
                accelerator_workers=lanes,
                show_progress=False,
                matmul_precision=matmul_precision,
                warmup_task_count=half_count,
                benchmark_timer=timer,
            )
        except (RuntimeError, NotImplementedError) as error:
            if lanes == 1:
                raise
            print(
                f"    {lanes} lanes unavailable: "
                f"{type(error).__name__}: {error}"
            )
            continue

        measured_rates[lanes] = half_count / timer.elapsed

    if not measured_rates:
        selected = 1
    else:
        fastest_rate = max(measured_rates.values())
        # Prefer the least concurrency within 3% of the fastest result. This
        # avoids extra memory use for differences smaller than tuning noise.
        selected = min(
            lanes
            for lanes, rate in measured_rates.items()
            if rate >= fastest_rate * 0.97
        )

    accelerator_lane_cache[cache_key] = selected
    measurements = ", ".join(
        f"{lanes}: {rate:.1f} pairs/s"
        for lanes, rate in sorted(measured_rates.items())
    )
    print(f"    {measurements}")
    print(f"  > Selected {selected} accelerator lane(s).")
    return selected


def process_accelerated_tasks(
    batch_tasks,
    workers,
    input_h5,
    device,
    batch_id,
    accelerator_workers=None,
    embedding_store=None,
    sequence_lengths=None,
    matmul_precision="ieee_fp32",
    execution_variant="scalar",
    result_callback=None,
):
    """
    Auto-select accelerator concurrency, then run the complete task batch.
    """
    if accelerator_workers is None:
        accelerator_workers = _select_accelerator_lanes(
            batch_tasks,
            workers,
            input_h5,
            device,
            batch_id,
            matmul_precision=matmul_precision,
        )
    if (
        execution_variant == "tiled"
        and embedding_store is not None
        and sequence_lengths is not None
    ):
        tiled_supported, support_reason = tiled_accelerator_support(
            device, require_memory=True
        )
        if not tiled_supported:
            raise RuntimeError(
                f"Tiled execution is unavailable on '{device}': "
                f"{support_reason}."
            )
        backend = get_accelerator_backend(device)
        backend_label = backend.device_type.upper()
        progress = tqdm(
            total=len(batch_tasks),
            desc=(
                f"  Batch {batch_id} (tiled {backend_label}, "
                f"{accelerator_workers} lane"
                f"{'s' if accelerator_workers != 1 else ''})"
            ),
            leave=False,
        )
        matrix_budget = None
        try:
            for attempt in range(4):
                checkpoint = (
                    result_callback.checkpoint()
                    if result_callback is not None
                    and hasattr(result_callback, "checkpoint")
                    else None
                )
                try:
                    return run_tiled_accelerator_pipeline(
                        batch_tasks,
                        store=embedding_store,
                        lengths=sequence_lengths,
                        device=device,
                        workers=workers,
                        lanes=accelerator_workers,
                        alignment_callback=calculate_alignment_data,
                        precision=matmul_precision,
                        progress=progress,
                        matrix_budget_override=matrix_budget,
                        result_callback=result_callback,
                    )
                except Exception as error:
                    if not backend.is_out_of_memory(error):
                        raise
                    if checkpoint is not None:
                        result_callback.rollback(checkpoint)
                    backend.empty_cache()
                    default_budget = cuda_memory_plan(
                        device,
                        lanes=accelerator_workers,
                    ).matrix_bytes
                    matrix_budget = max(
                        16 * 1024 * 1024,
                        int(matrix_budget or default_budget) // 2,
                    )
                    print(
                        f"  > {backend_label} memory pressure; retrying batch with "
                        f"{matrix_budget / (1024 ** 2):.0f} MiB matrix budget."
                    )
            print(
                f"  > Tiled {backend_label} remained out of memory; "
                f"using scalar {backend_label}."
            )
        finally:
            progress.close()
    return _run_accelerated_pipeline(
        batch_tasks,
        workers,
        input_h5,
        device,
        batch_id,
        accelerator_workers,
        show_progress=True,
        matmul_precision=matmul_precision,
        result_callback=result_callback,
    )


def process_cpu_tasks(
    batch_tasks,
    workers,
    input_h5,
    batch_id,
    show_progress=True,
    result_callback=None,
    warmup_task_count=0,
    benchmark_timer=None,
):
    """Process complete pairs in parallel when no accelerator is available."""
    batch_tasks = list(batch_tasks)
    warmup_task_count = int(warmup_task_count)
    if benchmark_timer is not None and (
        warmup_task_count < 0 or warmup_task_count >= len(batch_tasks)
    ):
        raise ValueError("Benchmark warm-up count must leave a timed task.")
    results = []
    with Pool(
        processes=workers,
        initializer=init_worker,
        initargs=(input_h5,),
    ) as pool:
        progress = tqdm(
            total=len(batch_tasks),
            desc=f"  Batch {batch_id}",
            leave=False,
            disable=not show_progress,
        )

        def run_phase(phase_tasks):
            iterator = pool.imap_unordered(
                calculate_cpu_pair,
                phase_tasks,
                chunksize=10,
            )
            for result in iterator:
                results.append(result)
                progress.update(1)
                if result_callback is not None and len(results) >= 65536:
                    result_callback(results)
                    results.clear()

        try:
            if benchmark_timer is None:
                run_phase(batch_tasks)
            else:
                if warmup_task_count:
                    run_phase(batch_tasks[:warmup_task_count])
                benchmark_timer.start()
                run_phase(batch_tasks[warmup_task_count:])
                benchmark_timer.stop()
        finally:
            progress.close()
    if result_callback is not None and results:
        result_callback(results)
        results.clear()
    return results


def _representative_pending_pairs(
    safe_headers,
    sequence_lengths,
    computed_mask,
    required_mask,
    num_tasks,
    limit,
):
    """Sample the complete pending workload, then stratify by estimated cost."""
    limit = max(1, min(int(limit), int(num_tasks)))
    probe_count = min(int(num_tasks), max(limit * 8, limit))
    target_ordinals = np.linspace(
        0, int(num_tasks) - 1, num=probe_count, dtype=np.int64
    )
    targets = set(int(value) for value in target_ordinals)
    probes = []
    ordinal = 0
    n_sequences = len(safe_headers)
    for row in range(n_sequences):
        columns = np.arange(row + 1, n_sequences)
        pending = ~computed_mask[row, row + 1:]
        if required_mask is not None:
            pending &= required_mask[row, row + 1:]
        for column in columns[pending]:
            if ordinal in targets:
                cost = int(sequence_lengths[row]) * int(sequence_lengths[column])
                probes.append(
                    (
                        cost,
                        (
                            row,
                            int(column),
                            safe_headers[row],
                            safe_headers[column],
                        ),
                    )
                )
            ordinal += 1

    probes.sort(key=lambda item: (item[0], item[1][0], item[1][1]))
    selected_indices = np.linspace(
        0, len(probes) - 1, num=min(limit, len(probes)), dtype=np.int64
    )
    return [probes[int(index)][1] for index in selected_indices]


def _first_pending_pairs(
    safe_headers,
    computed_mask,
    required_mask,
    num_tasks,
    limit,
):
    """Return the first production-ordered pending pairs."""
    limit = max(1, min(int(limit), int(num_tasks)))
    sample = []
    n_sequences = len(safe_headers)
    for row in range(n_sequences - 1):
        pending = ~computed_mask[row, row + 1:]
        if required_mask is not None:
            pending &= required_mask[row, row + 1:]
        columns = np.flatnonzero(pending) + row + 1
        for column in columns:
            column = int(column)
            sample.append(
                (row, column, safe_headers[row], safe_headers[column])
            )
            if len(sample) >= limit:
                return sample
    return sample


def _representative_row_local_pending_pairs(
    safe_headers,
    sequence_lengths,
    computed_mask,
    required_mask,
    num_tasks,
    limit,
):
    """Return a cost-stratified sample that retains production row locality."""
    limit = max(1, min(int(limit), int(num_tasks)))
    n_sequences = len(safe_headers)
    populated_rows = []
    pending_by_row = {}
    for row in range(n_sequences - 1):
        pending = ~computed_mask[row, row + 1:]
        if required_mask is not None:
            pending &= required_mask[row, row + 1:]
        columns = np.flatnonzero(pending) + row + 1
        if len(columns):
            populated_rows.append(row)
            pending_by_row[row] = columns
    if not populated_rows:
        return []

    row_count = min(8, len(populated_rows), limit)
    row_positions = np.linspace(
        0,
        len(populated_rows) - 1,
        num=row_count,
        dtype=np.int64,
    )
    selected_rows = [populated_rows[int(position)] for position in row_positions]
    per_row = max(1, math.ceil(limit / len(selected_rows)))
    sample = []
    for row in selected_rows:
        columns = pending_by_row[row]
        ordered = sorted(
            (int(column) for column in columns),
            key=lambda column: (
                int(sequence_lengths[row]) * int(sequence_lengths[column]),
                column,
            ),
        )
        positions = np.linspace(
            0,
            len(ordered) - 1,
            num=min(per_row, len(ordered)),
            dtype=np.int64,
        )
        for position in positions:
            column = ordered[int(position)]
            sample.append(
                (row, column, safe_headers[row], safe_headers[column])
            )
    return sample[:limit]


def _precision_device(candidates):
    manual = Hardware_Utils.resolve_device_selection(DEVICE_SELECTION, candidates)
    if manual is not None:
        return manual if manual.backend == "cuda" else None
    return next((candidate for candidate in candidates if candidate.backend == "cuda"), None)


def _execution_variants(candidate):
    """Return execution variants allowed for one hardware candidate."""
    mode = normalize_execution_mode(EXECUTION_MODE)
    tiled_supported = (
        candidate.backend in {"cuda", "xpu"}
        and tiled_accelerator_support(
            candidate.device, require_memory=False
        )[0]
    )
    if mode == "scalar":
        return ["scalar"]
    if mode == "tiled":
        return ["tiled"] if tiled_supported else []
    variants = ["scalar"]
    if tiled_supported:
        variants.append("tiled")
    return variants


def _validate_execution_mode_hardware():
    """Fail early when a forced execution mode cannot use selected hardware."""
    mode = normalize_execution_mode(EXECUTION_MODE)
    if mode != "tiled":
        return mode
    candidates = Hardware_Utils.get_available_devices()
    manual = Hardware_Utils.resolve_device_selection(
        DEVICE_SELECTION, candidates
    )
    if manual is not None and not _execution_variants(manual):
        raise ValueError(
            "Tiled execution requires a CUDA/ROCm or XPU accelerator; "
            "the selected device "
            f"is '{manual.spec}'."
        )
    eligible = [
        candidate for candidate in candidates if _execution_variants(candidate)
    ]
    if manual is not None:
        eligible = [manual]
    if not eligible:
        raise ValueError(
            "Tiled execution was requested, but no compatible CUDA/ROCm or "
            "XPU accelerator is available."
        )
    return mode


def _gib_text(byte_count):
    return f"{int(byte_count) / (1024 ** 3):.2f} GiB"


def _vram_estimate_text(estimate):
    return (
        f"projected {_gib_text(estimate.projected_peak_bytes)} / "
        f"safe {_gib_text(estimate.safe_peak_bytes)}; "
        f"tile {_gib_text(estimate.tile_bytes)}, "
        f"transient {_gib_text(estimate.transient_bytes)}, "
        f"per-slot cap {_gib_text(estimate.per_microbatch_bytes)}"
    )


def _resolve_active_matmul_precision(
    setting,
    cached_precision,
    sample,
    workers,
    store,
    sequence_lengths,
):
    """Resolve auto precision across the permitted CUDA execution variants."""
    normalized = normalize_precision_setting(setting)
    execution_mode = normalize_execution_mode(EXECUTION_MODE)
    variants = (
        ("scalar", "tiled")
        if execution_mode == "auto"
        else (execution_mode,)
    )
    if cached_precision is not None:
        print(f"[Precision] Resuming established {cached_precision} batches.")
        return cached_precision
    if normalized == "float32":
        return "ieee_fp32"

    candidates = Hardware_Utils.get_available_devices()
    cuda_candidate = _precision_device(candidates)
    if cuda_candidate is None:
        if normalized == "tf32":
            raise ValueError("TF32 was requested, but no CUDA device is available.")
        return "ieee_fp32"
    if normalized == "tf32":
        print("[Precision] TF32 was explicitly selected.")
        return "tf32"

    validation_tasks = list(
        sample[: min(int(PRECISION_VALIDATION_PAIRS), len(sample))]
    )
    if len(validation_tasks) < 2:
        return "ieee_fp32"
    Hardware_Utils.release_device_cache(cuda_candidate)
    memory_plan = cuda_memory_plan(cuda_candidate.device, lanes=1)
    memory_info = (memory_plan.free_bytes, memory_plan.total_bytes)
    preflight = {
        variant: estimate_cuda_working_set(
            validation_tasks,
            store=store,
            lengths=sequence_lengths,
            device=cuda_candidate.device,
            lanes=1,
            variant=variant,
            memory_info=memory_info,
        )
        for variant in variants
    }
    for variant, estimate in preflight.items():
        print(
            f"[Precision] VRAM preflight {variant}: "
            f"{_vram_estimate_text(estimate)}; {estimate.reason}."
        )
    infeasible = [
        f"{variant}: {estimate.reason}"
        for variant, estimate in preflight.items()
        if not estimate.feasible
    ]
    if infeasible:
        print(
            f"[Precision] Selected-plan validation is not VRAM-safe "
            f"({'; '.join(infeasible)}); using IEEE FP32."
        )
        return "ieee_fp32"
    print(
        f"[Precision] Testing FP32/TF32 with "
        f"{', '.join(variants)} CUDA execution on "
        f"{len(validation_tasks)} production-ordered pairs..."
    )

    def run_variant(variant, precision, tasks):
        if variant == "scalar":
            return _run_accelerated_pipeline(
                tasks,
                workers,
                store.path,
                cuda_candidate.device,
                0,
                accelerator_workers=1,
                show_progress=False,
                matmul_precision=precision,
            )
        return run_tiled_cuda_pipeline(
            tasks,
            store=store,
            lengths=sequence_lengths,
            device=cuda_candidate.device,
            workers=workers,
            lanes=1,
            alignment_callback=calculate_alignment_data,
            precision=precision,
        )

    try:
        for variant in variants:
            run_variant(variant, "float32", validation_tasks[:2])

        results_by_plan = {}
        rates = {}
        print("Plan       Precision   Throughput (pairs/s)")
        for variant in variants:
            for precision in ("float32", "tf32"):
                started = time.perf_counter()
                results_by_plan[(variant, precision)] = run_variant(
                    variant,
                    precision,
                    validation_tasks,
                )
                elapsed = max(time.perf_counter() - started, 1e-9)
                rates[(variant, precision)] = len(validation_tasks) / elapsed
                print(
                    f"{variant:10} {precision:9} "
                    f"{rates[(variant, precision)]:>20.2f}"
                )
    except Exception as error:
        print(
            f"[Precision] TF32 validation unavailable "
            f"({type(error).__name__}: {error}); using IEEE FP32."
        )
        return "ieee_fp32"

    validation = {}
    for variant in variants:
        validation[variant] = compare_precision_results(
            results_by_plan[(variant, "float32")],
            results_by_plan[(variant, "tf32")],
        )

    fp32_best = max(rates[(variant, "float32")] for variant in variants)
    tf32_best = max(rates[(variant, "tf32")] for variant in variants)
    speedup = tf32_best / max(fp32_best, 1e-9)
    all_equivalent = all(equivalent for equivalent, _reason in validation.values())
    if all_equivalent and speedup >= 1.10:
        print(
            f"[Precision] TF32 passed {', '.join(variants)} numerical validation "
            f"and its best plan was {speedup:.2f}x faster."
        )
        return "tf32"

    if not all_equivalent:
        failed = next(
            f"{variant}: {reason}"
            for variant, (equivalent, reason) in validation.items()
            if not equivalent
        )
        speed_reason = f"numerical validation failed for {failed}"
    else:
        speed_reason = f"best-plan speedup {speedup:.2f}x is below 1.10x"
    print(f"[Precision] Using IEEE FP32: {speed_reason}.")
    return "ieee_fp32"


def _benchmark_processing_plans(
    batch_tasks,
    workers,
    input_h5,
    batch_id,
    embedding_store=None,
    sequence_lengths=None,
    matmul_precision=None,
    warmup_task_count=0,
):
    """Compare the complete CPU path with every accelerator/lane plan."""
    execution_mode = normalize_execution_mode(EXECUTION_MODE)
    candidates = Hardware_Utils.get_available_devices()
    if matmul_precision is None:
        matmul_precision = active_matmul_precision
    if matmul_precision == "tf32":
        candidates = [candidate for candidate in candidates if candidate.backend == "cuda"]
        if not candidates:
            raise RuntimeError("TF32 execution requires an available CUDA device.")
    manual = Hardware_Utils.resolve_device_selection(
        DEVICE_SELECTION, candidates
    )
    if execution_mode == "tiled":
        if manual is not None and not _execution_variants(manual):
            raise ValueError(
                "Tiled execution requires a CUDA/ROCm or XPU accelerator; "
                "the selected device "
                f"is '{manual.spec}'."
            )
        candidates = [
            candidate for candidate in candidates
            if _execution_variants(candidate)
        ]
        if not candidates:
            raise ValueError(
                "Tiled execution was requested, but no compatible CUDA/ROCm "
                "or XPU accelerator is available."
            )
    if manual is not None and manual.is_cpu:
        print(f"[Hardware] Using manually selected {manual.display_name}.")
        return [Hardware_Utils.BenchmarkResult(manual, 0.0, variant="scalar")]

    accelerator_tasks = list(batch_tasks)
    warmup_task_count = int(warmup_task_count)
    accelerator_warmup = accelerator_tasks[:warmup_task_count]
    accelerator_timed = accelerator_tasks[warmup_task_count:]
    if not accelerator_timed:
        raise ValueError("The hardware benchmark requires at least one timed pair.")
    _accelerator_half, cpu_half = _benchmark_half_sizes()
    cpu_warmup = evenly_spaced_task_subset(accelerator_warmup, cpu_half)
    cpu_timed = evenly_spaced_task_subset(accelerator_timed, cpu_half)
    cpu_tasks = cpu_warmup + cpu_timed

    def execute_plan(candidate, variant, lanes, tasks, phase_count, timer):
        if candidate.is_cpu:
            return process_cpu_tasks(
                tasks,
                workers,
                input_h5,
                batch_id,
                show_progress=False,
                warmup_task_count=phase_count,
                benchmark_timer=timer,
            )
        if variant == "tiled":
            return run_tiled_accelerator_pipeline(
                tasks,
                store=embedding_store,
                lengths=sequence_lengths,
                device=candidate.device,
                workers=workers,
                lanes=lanes,
                alignment_callback=calculate_alignment_data,
                precision=matmul_precision,
                warmup_task_count=phase_count,
                benchmark_timer=timer,
            )
        return _run_accelerated_pipeline(
            tasks,
            workers,
            input_h5,
            candidate.device,
            batch_id,
            accelerator_workers=lanes,
            show_progress=False,
            matmul_precision=matmul_precision,
            warmup_task_count=phase_count,
            benchmark_timer=timer,
        )

    if manual is not None:
        candidates = [manual]
        print(
            f"[Hardware] Benchmarking plans on manually selected "
            f"{manual.display_name}."
        )

    print(
        f"[Hardware] Benchmarking {len(candidates)} device(s): CUDA/XPU "
        f"{len(accelerator_warmup)} warm + {len(accelerator_timed)} timed; "
        f"CPU/other {len(cpu_warmup)} warm + {len(cpu_timed)} timed."
    )
    print(
        "Device/backend                 Plan      Lanes   VRAM peak/safe   "
        "Throughput (pairs/s)   Status"
    )
    results = []
    for candidate in candidates:
        candidate_results = []
        if candidate.backend in {"cuda", "xpu"}:
            sample = accelerator_tasks
            phase_count = len(accelerator_warmup)
            timed_count = len(accelerator_timed)
        else:
            sample = cpu_tasks
            phase_count = len(cpu_warmup)
            timed_count = len(cpu_timed)
        candidate_memory_info = None
        if (
            candidate.backend in {"cuda", "xpu"}
            and tiled_accelerator_support(
                candidate.device, require_memory=True
            )[0]
            and embedding_store is not None
            and sequence_lengths is not None
        ):
            Hardware_Utils.release_device_cache(candidate)
            base_memory_plan = cuda_memory_plan(candidate.device, lanes=1)
            candidate_memory_info = (
                base_memory_plan.free_bytes,
                base_memory_plan.total_bytes,
            )
        lane_candidates = (
            [1]
            if candidate.is_cpu
            else _accelerator_lane_candidates(candidate.device, workers)
        )
        variants = _execution_variants(candidate)
        if "tiled" in variants and (
            embedding_store is None or sequence_lengths is None
        ):
            variants.remove("tiled")

        for variant in variants:
            for lanes in lane_candidates:
                memory_estimate = None
                vram_label = "--"
                if candidate_memory_info is not None:
                    memory_estimate = estimate_cuda_working_set(
                        sample,
                        store=embedding_store,
                        lengths=sequence_lengths,
                        device=candidate.device,
                        lanes=lanes,
                        variant=variant,
                        memory_info=candidate_memory_info,
                    )
                    vram_label = (
                        f"{memory_estimate.projected_peak_bytes / (1024 ** 3):.1f}/"
                        f"{memory_estimate.safe_peak_bytes / (1024 ** 3):.1f}G"
                    )
                    if not memory_estimate.feasible:
                        result = Hardware_Utils.BenchmarkResult(
                            candidate,
                            None,
                            lanes=lanes,
                            error=f"VRAM preflight: {memory_estimate.reason}",
                            variant=variant,
                        )
                        print(
                            f"{candidate.display_name[:30]:30}  {variant:8}  "
                            f"{lanes:>5}   {vram_label:>14}   "
                            f"{'--':>20}   skipped: {memory_estimate.reason}"
                        )
                        candidate_results.append(result)
                        continue
                timer = BenchmarkPhaseTimer()
                try:
                    execute_plan(
                        candidate,
                        variant,
                        lanes,
                        sample,
                        phase_count,
                        timer,
                    )
                    elapsed = timer.elapsed
                    rate = timed_count / elapsed
                    result = Hardware_Utils.BenchmarkResult(
                        candidate,
                        rate,
                        lanes=lanes,
                        variant=variant,
                    )
                    print(
                        f"{candidate.display_name[:30]:30}  {variant:8}  "
                        f"{lanes:>5}   {vram_label:>14}   "
                        f"{rate:>20.2f}   ok ({timed_count} pairs, "
                        f"{elapsed:.3f}s)"
                    )
                except Exception as error:
                    result = Hardware_Utils.BenchmarkResult(
                        candidate,
                        None,
                        lanes=lanes,
                        error=f"{type(error).__name__}: {error}",
                        variant=variant,
                    )
                    print(
                        f"{candidate.display_name[:30]:30}  {variant:8}  "
                        f"{lanes:>5}   {vram_label:>14}   "
                        f"{'--':>20}   {result.error}"
                    )
                candidate_results.append(result)
        results.extend(candidate_results)
        Hardware_Utils.release_device_cache(candidate)

    ranked = Hardware_Utils.rank_benchmark_results(
        results, higher_is_better=True
    )
    if not ranked:
        raise RuntimeError("No CPU or accelerator alignment plan completed.")
    winner = ranked[0]
    fastest = max(
        (result for result in results if result.succeeded),
        key=lambda result: float(result.value),
    )
    tie_applied = (
        winner.candidate.spec != fastest.candidate.spec
        or winner.lanes != fastest.lanes
        or winner.variant != fastest.variant
    )
    print(
        f"[Hardware] Selected {winner.candidate.display_name} with "
        f"{winner.variant} plan and {winner.lanes} lane(s); 3% tie preference "
        f"{'applied' if tie_applied else 'not applied'}."
    )
    return ranked


def _run_batch_with_ranked_plans(
    ranked_plans,
    active_plan_index,
    *process_args,
    **process_kwargs,
):
    """Run one uncommitted batch, failing over only in automatic mode."""
    while active_plan_index < len(ranked_plans):
        plan = ranked_plans[active_plan_index]
        try:
            process_batch(
                *process_args,
                **process_kwargs,
                device=plan.candidate.device,
                accelerator_workers=(
                    None if plan.candidate.is_cpu else plan.lanes
                ),
                execution_variant=plan.variant,
            )
            return active_plan_index
        except (RuntimeError, NotImplementedError, MemoryError) as error:
            if Hardware_Utils.normalize_device_selection(DEVICE_SELECTION) != "auto":
                raise RuntimeError(
                    f"Alignment batch failed on manually selected device "
                    f"'{plan.candidate.spec}': {error}"
                ) from error
            active_plan_index += 1
            if active_plan_index >= len(ranked_plans):
                raise RuntimeError(
                    "Every benchmarked alignment processing plan failed."
                ) from error
            fallback = ranked_plans[active_plan_index]
            print(
                f"[Hardware] {type(error).__name__}; retrying batch on "
                f"{fallback.candidate.display_name}, lanes={fallback.lanes}."
            )
    raise RuntimeError("No alignment processing plan is available.")


# %% =======================================
# PROCESSING & MERGE
# ==========================================
class _PartialBatchWriter:
    """Append result chunks and atomically publish one complete batch."""

    DATASET_DTYPES = {
        "i": np.uint32,
        "j": np.uint32,
        "l_score": np.float32,
        "l_len": np.uint16,
        "g_score": np.float32,
        "g_len": np.uint16,
    }

    def __init__(
        self,
        output_filename,
        embedding_checksum,
        model_name,
        gap_penalties,
        matmul_precision,
    ):
        self.output_filename = output_filename
        self.partial_filename = output_filename + ".partial"
        if os.path.exists(self.partial_filename):
            os.remove(self.partial_filename)
        self.hf = h5py.File(self.partial_filename, "w")
        if embedding_checksum is not None:
            self.hf.attrs["embedding_checksum"] = embedding_checksum
        if model_name is not None:
            self.hf.attrs["model_name"] = model_name
        if gap_penalties is not None:
            self.hf.attrs["gap_penalties"] = np.asarray(
                gap_penalties, dtype=np.float32
            )
        self.hf.attrs["matmul_precision"] = matmul_precision
        self.datasets = {
            name: self.hf.create_dataset(
                name,
                shape=(0,),
                maxshape=(None,),
                dtype=dtype,
            )
            for name, dtype in self.DATASET_DTYPES.items()
        }
        self.count = 0
        self.closed = False

    def checkpoint(self):
        return self.count

    def rollback(self, count):
        count = int(count)
        for dataset in self.datasets.values():
            dataset.resize((count,))
        self.count = count
        self.hf.flush()

    def __call__(self, results):
        if not results:
            return
        start = self.count
        end = start + len(results)
        for dataset in self.datasets.values():
            dataset.resize((end,))
        columns = tuple(zip(*results))
        for column, (name, dtype) in zip(
            columns,
            self.DATASET_DTYPES.items(),
        ):
            self.datasets[name][start:end] = np.asarray(column, dtype=dtype)
        self.count = end

    def publish(self):
        self.hf.flush()
        self.hf.close()
        self.closed = True
        os.replace(self.partial_filename, self.output_filename)

    def close(self):
        if not self.closed:
            self.hf.close()
            self.closed = True


def process_batch(
    batch_tasks,
    batch_id,
    workers,
    input_h5,
    embedding_checksum,
    model_name=None,
    saving_mode=None,
    gap_penalties=None,
    device=None,
    accelerator_workers=None,
    execution_variant="scalar",
    matmul_precision=None,
    embedding_store=None,
    sequence_lengths=None,
):
    output_filename = os.path.join(RESULTS_DIR, f"batch_{batch_id:05d}.h5")
    if device is None:
        device = Hardware_Utils.get_optimal_device()
    if matmul_precision is None:
        matmul_precision = active_matmul_precision
    if embedding_store is None:
        embedding_store = active_embedding_store
    if sequence_lengths is None:
        sequence_lengths = active_sequence_lengths

    writer = _PartialBatchWriter(
        output_filename,
        embedding_checksum,
        model_name,
        gap_penalties,
        matmul_precision,
    )
    try:
        if _uses_accelerator(device):
            results = process_accelerated_tasks(
                batch_tasks,
                workers,
                input_h5,
                device,
                batch_id,
                accelerator_workers=accelerator_workers,
                embedding_store=embedding_store,
                sequence_lengths=sequence_lengths,
                matmul_precision=matmul_precision,
                execution_variant=execution_variant,
                result_callback=writer,
            )
        else:
            results = process_cpu_tasks(
                batch_tasks,
                workers,
                input_h5,
                batch_id,
                result_callback=writer,
            )
        writer(results)
        if writer.count != len(batch_tasks):
            raise RuntimeError(
                f"Batch produced {writer.count} results for "
                f"{len(batch_tasks)} requested pairs."
            )
        writer.publish()
    finally:
        writer.close()

def _decode_attr(val):
    if val is None:
        return None
    if isinstance(val, bytes):
        return val.decode("utf-8")
    return str(val)

def _compare_gap_penalties(cached_gap, current_gap):
    if cached_gap is None:
        return False
    try:
        cached_arr = np.array(cached_gap, dtype=np.float32).flatten()
        current_arr = np.array(current_gap, dtype=np.float32).flatten()
        return len(cached_arr) == len(current_arr) and np.allclose(cached_arr, current_arr, atol=1e-5)
    except Exception:
        return False

def scan_existing_batches(
    n,
    current_checksum,
    model_name,
    saving_mode,
    gap_penalties,
    computed_mask,
    requested_matmul_precision=None,
):
    if not os.path.exists(RESULTS_DIR):
        os.makedirs(RESULTS_DIR, exist_ok=True)
        return None
    
    batch_files = glob.glob(os.path.join(glob.escape(RESULTS_DIR), "batch_*.h5"))
    if not batch_files:
        return None

    mismatches = []
    found_attrs = {
        "model_name": "Unknown/Legacy",
        "gap_penalties": "Unknown/Legacy",
        "embedding_checksum": "Unknown/Legacy",
        "matmul_precision": "ieee_fp32",
    }
    established_precision = None

    for bf in batch_files:
        try:
            with h5py.File(bf, "r") as hf:
                cached_checksum = _decode_attr(hf.attrs.get("embedding_checksum"))
                cached_model = _decode_attr(hf.attrs.get("model_name"))
                cached_gaps = hf.attrs.get("gap_penalties")
                cached_precision = _decode_attr(
                    hf.attrs.get("matmul_precision", "ieee_fp32")
                )

                if cached_checksum: found_attrs["embedding_checksum"] = cached_checksum
                if cached_model: found_attrs["model_name"] = cached_model
                if cached_gaps is not None: found_attrs["gap_penalties"] = list(np.array(cached_gaps, dtype=np.float32).flatten())
                found_attrs["matmul_precision"] = cached_precision

                # Check for completeness of datasets
                required_keys = ["i", "j", "l_score", "l_len", "g_score", "g_len"]
                if not all(k in hf for k in required_keys):
                    mismatches.append(f"Missing required datasets in batch file '{os.path.basename(bf)}'")
                    break

                len_i = len(hf["i"])
                if any(len(hf[k]) != len_i for k in ["j", "l_score", "l_len", "g_score", "g_len"]):
                    mismatches.append(f"Dataset length mismatch in batch file '{os.path.basename(bf)}'")
                    break

                # Attribute checks
                if cached_checksum != current_checksum:
                    mismatches.append(f"Checksum mismatch in '{os.path.basename(bf)}' ('{cached_checksum}' vs current '{current_checksum}')")
                    break
                if cached_model != model_name:
                    mismatches.append(f"Model name mismatch in '{os.path.basename(bf)}' ('{cached_model}' vs current '{model_name}')")
                    break
                if not _compare_gap_penalties(cached_gaps, gap_penalties):
                    mismatches.append(f"Gap penalties mismatch in '{os.path.basename(bf)}' ({found_attrs['gap_penalties']} vs current {gap_penalties})")
                    break
                if established_precision is None:
                    established_precision = cached_precision
                elif cached_precision != established_precision:
                    mismatches.append(
                        f"Mixed matmul precision in '{os.path.basename(bf)}' "
                        f"('{cached_precision}' vs '{established_precision}')"
                    )
                    break
                if (
                    requested_matmul_precision is not None
                    and cached_precision != requested_matmul_precision
                ):
                    mismatches.append(
                        f"Matmul precision mismatch in '{os.path.basename(bf)}' "
                        f"('{cached_precision}' vs current "
                        f"'{requested_matmul_precision}')"
                    )
                    break
        except Exception as e:
            mismatches.append(f"Error reading batch file '{os.path.basename(bf)}': {e}")
            break

    if mismatches:
        # Determine unique backup folder path
        backup_dir = f"{RESULTS_DIR}_BackUp"
        counter = 1
        while os.path.exists(backup_dir):
            backup_dir = f"{RESULTS_DIR}_BackUp_{counter}"
            counter += 1

        print(f"\n⚠️ WARNING: Existing batch cache directory '{RESULTS_DIR}' contains mismatched or incomplete batches.")
        print(f"  > Mismatch reason: {mismatches[0]}")
        print(f"  > Renaming existing batch folder to: '{backup_dir}'")

        try:
            shutil.move(RESULTS_DIR, backup_dir)
        except Exception as err:
            print(f"⚠️ Error renaming directory {RESULTS_DIR} to {backup_dir}: {err}")

        # Create informative text report inside the backup folder
        info_file = os.path.join(backup_dir, "batch_attributes_info.txt")
        try:
            os.makedirs(backup_dir, exist_ok=True)
            with open(info_file, "w", encoding="utf-8", newline="\n") as info_f:
                info_f.write("==========================================================\n")
                info_f.write("ALIGNMENT BATCH DIRECTORY BACKUP REPORT\n")
                info_f.write("==========================================================\n")
                info_f.write(f"Backup Timestamp:    {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
                info_f.write(f"Original Directory:  {RESULTS_DIR}\n")
                info_f.write(f"Backup Directory:    {backup_dir}\n\n")
                info_f.write("REASON(S) FOR BACKUP:\n")
                for m in mismatches:
                    info_f.write(f"  - {m}\n")
                info_f.write("\nATTRIBUTES DETECTED IN BACKED-UP BATCHES:\n")
                info_f.write(f"  - Model Name:         {found_attrs['model_name']}\n")
                info_f.write(f"  - Gap Penalties:      {found_attrs['gap_penalties']}\n")
                info_f.write(f"  - Embedding Checksum: {found_attrs['embedding_checksum']}\n\n")
                info_f.write(f"  - Matmul Precision:   {found_attrs['matmul_precision']}\n\n")
                info_f.write("CURRENT EXECUTION SETTINGS:\n")
                info_f.write(f"  - Model Name:         {model_name}\n")
                info_f.write(f"  - Gap Penalties:      {gap_penalties}\n")
                info_f.write(f"  - Embedding Checksum: {current_checksum}\n")
                info_f.write(
                    f"  - Matmul Precision:   "
                    f"{requested_matmul_precision or 'auto'}\n"
                )
                info_f.write("==========================================================\n")
            print(f"  > Created attribute report: '{info_file}'")
        except Exception as err:
            print(f"⚠️ Error creating info file '{info_file}': {err}")

        # Re-initialize clean working directory
        os.makedirs(RESULTS_DIR, exist_ok=True)
        print(f"  > Initialized fresh calculation directory: '{RESULTS_DIR}'\n")
        return None

    # If all existing batches match current settings perfectly, populate computed_mask
    for bf in batch_files:
        try:
            with h5py.File(bf, "r") as hf:
                arr_i = hf["i"][:]
                arr_j = hf["j"][:]
                computed_mask[arr_i, arr_j] = True
                computed_mask[arr_j, arr_i] = True
        except Exception:
            pass
    return established_precision


def _count_computed_required_pairs(computed_mask, required_mask):
    """Count unique cached pairs represented by the active workload mask."""
    if required_mask is not None:
        # Sparse required masks contain only canonical upper-triangle entries.
        return int(np.count_nonzero(computed_mask & required_mask))
    return int(np.count_nonzero(computed_mask) // 2)

def compile_final_output(
    headers,
    seq_lens,
    required_mask,
    n,
    current_checksum,
    model_name,
    saving_mode,
    gap_penalties,
    matmul_precision="ieee_fp32",
):
    if not isinstance(model_name, str) or not model_name.strip():
        raise ValueError(
            "Cannot publish an alignment network without nonempty model_name metadata."
        )
    model_name = model_name.strip()
    print(f"\n--- Compiling Final HDF5 Output (Deduplicated) ---")
    
    num_seqs = len(headers)
    idx_dtype = np.uint16 if num_seqs <= 65535 else np.uint32
    
    batch_files = sorted(glob.glob(os.path.join(glob.escape(RESULTS_DIR), "batch_*.h5")))
    
    # We use a 2D mask to track which pairs are successfully written to avoid duplicates
    compiled_mask = np.zeros((n, n), dtype=bool)
    
    # First Pass: Count the total number of unique, valid edges to write
    total_edges = 0
    for bf in tqdm(batch_files, desc="Counting unique edges"):
        try:
            with h5py.File(bf, "r") as hf:
                arr_i = hf["i"][:]
                arr_j = hf["j"][:]
                
                # Filter out elements that do not pass pre-filtering
                if required_mask is not None:
                    valid_mask = required_mask[arr_i, arr_j]
                    arr_i = arr_i[valid_mask]
                    arr_j = arr_j[valid_mask]
                
                # Find which ones are not yet compiled
                uncompiled = ~compiled_mask[arr_i, arr_j]
                unique_i = arr_i[uncompiled]
                unique_j = arr_j[uncompiled]
                
                # Mark as compiled in the first pass
                compiled_mask[unique_i, unique_j] = True
                compiled_mask[unique_j, unique_i] = True
                total_edges += len(unique_i)
        except Exception as e:
            print(f"Warning: Error reading {bf} during counting: {e}")
            
    print(f"Saving Combined Scores to {FINAL_OUTPUT_NET} (Total unique edges: {total_edges})...")
    os.makedirs(os.path.dirname(FINAL_OUTPUT_NET), exist_ok=True)
    
    # Reset compiled_mask for the actual write pass
    compiled_mask.fill(False)
    
    with h5py.File(FINAL_OUTPUT_NET, "w") as hf_out:
        if current_checksum is not None:
            hf_out.attrs["embedding_checksum"] = current_checksum
        hf_out.attrs["model_name"] = model_name
        if gap_penalties is not None:
            hf_out.attrs["gap_penalties"] = np.array(gap_penalties, dtype=np.float32)
        hf_out.attrs["matmul_precision"] = matmul_precision

        dt_str = h5py.string_dtype(encoding='utf-8')
        hf_out.create_dataset("headers", data=np.array(headers, dtype=object), dtype=dt_str)
        hf_out.create_dataset("seq_lens", data=np.array(seq_lens, dtype=np.uint16))
        
        # Pre-allocate datasets
        hf_out.create_dataset("i", shape=(total_edges,), dtype=idx_dtype)
        hf_out.create_dataset("j", shape=(total_edges,), dtype=idx_dtype)
        hf_out.create_dataset("l_score", shape=(total_edges,), dtype=np.float32)
        hf_out.create_dataset("l_len", shape=(total_edges,), dtype=np.uint16)
        hf_out.create_dataset("g_score", shape=(total_edges,), dtype=np.float32)
        hf_out.create_dataset("g_len", shape=(total_edges,), dtype=np.uint16)
        
        curr_idx = 0
        for bf in tqdm(batch_files, desc="Merging batches"):
            try:
                with h5py.File(bf, "r") as hf_in:
                    arr_i = hf_in["i"][:]
                    arr_j = hf_in["j"][:]
                    
                    uncompiled = ~compiled_mask[arr_i, arr_j]
                    if required_mask is not None:
                        uncompiled &= required_mask[arr_i, arr_j]
                        
                    n_write = np.sum(uncompiled)
                    if n_write == 0:
                        continue
                        
                    end_idx = curr_idx + n_write
                    
                    hf_out["i"][curr_idx:end_idx] = arr_i[uncompiled]
                    hf_out["j"][curr_idx:end_idx] = arr_j[uncompiled]
                    hf_out["l_score"][curr_idx:end_idx] = hf_in["l_score"][:][uncompiled]
                    hf_out["l_len"][curr_idx:end_idx] = hf_in["l_len"][:][uncompiled]
                    hf_out["g_score"][curr_idx:end_idx] = hf_in["g_score"][:][uncompiled]
                    hf_out["g_len"][curr_idx:end_idx] = hf_in["g_len"][:][uncompiled]
                    
                    # Mark as compiled
                    compiled_mask[arr_i[uncompiled], arr_j[uncompiled]] = True
                    compiled_mask[arr_j[uncompiled], arr_i[uncompiled]] = True
                    
                    curr_idx = end_idx
            except Exception as e:
                print(f"Warning: Error merging batch {bf}: {e}")
                
    print("✅ Compilation complete!")

# %% =======================================
# MAIN
# ==========================================
def run_job_distributor():
    global active_matmul_precision, active_embedding_store
    global active_sequence_lengths
    try:
        _validate_execution_mode_hardware()
        normalize_precision_setting(ACCELERATOR_PRECISION)
        configure_runtime_paths()
    except ValueError as error:
        print(f"\n❌ Cannot start alignment:\n{error}")
        return

    if os.path.exists(FINAL_OUTPUT_NET):
        print("✅ Job already done."); return

    try: set_start_method('spawn')
    except RuntimeError: pass

    print(f"Loading Metadata from {FULL_INPUT_HDF5}...")
    if not os.path.exists(FULL_INPUT_HDF5): print("Embeddings file not found."); return

    print("Validating embedding metadata and sequence lengths...")
    try:
        headers, safe_headers, seq_lens, manifest = load_embedding_metadata(
            FULL_INPUT_HDF5
        )
    except EmbeddingFileError as error:
        print(f"\n❌ Cannot start alignment:\n{error}")
        return

    current_model_name = manifest.model_name
    current_saving_mode = manifest.saving_mode
    current_gap_penalties = [LOCAL_GAP_P, GLOBAL_GAP_P]
    precision_setting = normalize_precision_setting(ACCELERATOR_PRECISION)
    requested_cache_precision = {
        "float32": "ieee_fp32",
        "tf32": "tf32",
    }.get(precision_setting)

    n = len(headers)
    total_pairs = (n * (n - 1)) // 2
    
    # Prefiltering logic
    required_mask = None
    if EDGE_PREFILTERING and PREFILTER_STRENGTH > 0 and n >= 2:
        print(f"\n--- 🛠️ Edge Prefiltering: Calculating {POOLING_METHOD} Pooled Length-Adjusted Similarities ---")
        mean_embs = []
        with h5py.File(FULL_INPUT_HDF5, "r") as hf:
            for h in tqdm(safe_headers, desc=f"Pooling Embeddings ({POOLING_METHOD})"):
                emb = hf["embeddings"][h][:]
                if POOLING_METHOD == "max":
                    pooled = np.max(emb, axis=0)
                else:
                    pooled = np.mean(emb, axis=0)
                mean_embs.append(pooled)
        mean_embs = np.array(mean_embs, dtype=np.float32)
        
        # Calculate all-vs-all cosine similarities on CPU
        norms = np.linalg.norm(mean_embs, axis=1, keepdims=True)
        norms = np.where(norms == 0, 1e-8, norms)
        norm_embs = mean_embs / norms
        cos_sim = np.clip(np.dot(norm_embs, norm_embs.T), -1.0, 1.0)
        
        # Apply sequence length ratio adjustment
        seq_lens_array = np.array(seq_lens, dtype=np.int32)
        lens_col = seq_lens_array[:, np.newaxis]
        lens_row = seq_lens_array[np.newaxis, :]
        min_lens = np.minimum(lens_col, lens_row)
        max_lens = np.maximum(lens_col, lens_row)
        max_lens = np.maximum(max_lens, 1)
        length_ratio_mat = min_lens / max_lens
        
        if LENGTH_RATIO_POWER != 1.0:
            length_ratio_mat = length_ratio_mat ** LENGTH_RATIO_POWER
            
        cos_sim = cos_sim * length_ratio_mat
        
        # Memory-efficient percentile extraction
        mask = np.triu(np.ones((n, n), dtype=bool), k=1)
        triu_values = cos_sim[mask]
        del mask
        
        threshold = np.percentile(triu_values, PREFILTER_STRENGTH)
        del triu_values
        
        # Get indices of kept pairs
        mask = np.triu(np.ones((n, n), dtype=bool), k=1)
        required_mask = (cos_sim >= threshold) & mask
        del mask, cos_sim
        
        num_kept = np.sum(required_mask)
        print(f"  > Prefilter Strength: {PREFILTER_STRENGTH}%")
        print(f"  > Adjusted Similarity Threshold: {threshold:.6f}")
        print(f"  > Retaining {num_kept} / {total_pairs} pairs ({100.0 * num_kept / total_pairs:.2f}%)")
        print("-----------------------------------------------------------\n")

    # Allocate computed mask
    computed_mask = np.zeros((n, n), dtype=bool)

    # Calculate checksum of the input embedding file to validate cache
    print("Calculating checksum of input embedding file...")
    current_checksum = calculate_file_hash(FULL_INPUT_HDF5)
    print(f"  > Checksum: {current_checksum}")

    # Scan existing batches for already computed pairs
    cached_precision = scan_existing_batches(
        n,
        current_checksum,
        current_model_name,
        current_saving_mode,
        current_gap_penalties,
        computed_mask,
        requested_matmul_precision=requested_cache_precision,
    )

    # Find the next available batch_id
    existing_batches = glob.glob(os.path.join(glob.escape(RESULTS_DIR), "batch_*.h5"))
    batch_ids = []
    for f in existing_batches:
        base = os.path.basename(f)
        try:
            num = int(base.split("_")[1].split(".")[0])
            batch_ids.append(num)
        except:
            pass
    next_batch_id = max(batch_ids) + 1 if batch_ids else 0

    # Calculate stats
    effective_total_pairs = np.sum(required_mask) if required_mask is not None else total_pairs
    num_computed_and_required = _count_computed_required_pairs(
        computed_mask,
        required_mask,
    )

    num_tasks = effective_total_pairs - num_computed_and_required
    print(f"Total Required pairs: {effective_total_pairs}")
    print(f"Already computed pairs: {num_computed_and_required}")
    print(f"Pairs queued for calculation: {num_tasks}")

    # Build queue of missing tasks and process on the fly
    if num_tasks > 0:
        current_batch = []
        batch_id = next_batch_id
        active_plan_index = 0
        def pending_columns_for_row(row):
            pending = ~computed_mask[row, row + 1:]
            if required_mask is not None:
                pending &= required_mask[row, row + 1:]
            return np.flatnonzero(pending) + row + 1

        manual_candidate = Hardware_Utils.resolve_device_selection(
            DEVICE_SELECTION,
            Hardware_Utils.get_available_devices(),
        )
        if manual_candidate is not None and manual_candidate.is_cpu:
            benchmark_warmup = []
            benchmark_timed = _first_pending_pairs(
                safe_headers, computed_mask, required_mask, num_tasks, 1
            )
        else:
            pending_counts = np.zeros(n, dtype=np.int64)
            for row in range(n - 1):
                pending_counts[row] = len(pending_columns_for_row(row))
            accelerator_half, _cpu_half = _benchmark_half_sizes()
            benchmark_warmup, benchmark_timed = matched_benchmark_task_halves(
                safe_headers,
                seq_lens,
                pending_counts,
                pending_columns_for_row,
                accelerator_half,
            )
        benchmark_tasks = benchmark_warmup + benchmark_timed
        precision_half = min(
            int(PRECISION_VALIDATION_PAIRS) // 2,
            len(benchmark_warmup),
            len(benchmark_timed),
        )
        precision_tasks = (
            evenly_spaced_task_subset(benchmark_warmup, precision_half)
            + evenly_spaced_task_subset(benchmark_timed, precision_half)
        )
        try:
            active_embedding_store = EmbeddingTileStore(
                FULL_INPUT_HDF5,
                safe_headers,
                HOST_CACHE_GB,
            )
        except ValueError as error:
            print(f"\n❌ Invalid adaptive alignment configuration:\n{error}")
            return
        active_sequence_lengths = list(seq_lens)
        cache_mode = (
            f"packed host cache ({active_embedding_store.cached_bytes / (1024 ** 3):.2f} GiB)"
            if active_embedding_store.fully_cached
            else "memory-bounded HDF5 tiles"
        )
        print(f"[Memory] Using {cache_mode}.")
        try:
            active_matmul_precision = _resolve_active_matmul_precision(
                precision_setting,
                cached_precision,
                precision_tasks,
                WORKERS,
                active_embedding_store,
                active_sequence_lengths,
            )
        except ValueError as error:
            print(f"\n❌ Invalid precision configuration:\n{error}")
            return
        ranked_plans = _benchmark_processing_plans(
            benchmark_tasks,
            WORKERS,
            FULL_INPUT_HDF5,
            batch_id,
            embedding_store=active_embedding_store,
            sequence_lengths=active_sequence_lengths,
            matmul_precision=active_matmul_precision,
            warmup_task_count=len(benchmark_warmup),
        )
        batches_to_run = math.ceil(num_tasks / BATCH_SIZE)
        pbar = tqdm(
            total=batches_to_run,
            desc="Overall Progress",
            unit="batch",
        )
        
        for i in range(n):
            cols = np.arange(i + 1, n)
            
            row_computed = computed_mask[i, i+1:]
            if required_mask is not None:
                row_required = required_mask[i, i+1:]
                pending_mask = row_required & (~row_computed)
            else:
                pending_mask = ~row_computed
                
            if not np.any(pending_mask):
                continue
                
            pending_cols = cols[pending_mask]
            for j_val in pending_cols:
                current_batch.append((i, int(j_val), safe_headers[i], safe_headers[j_val]))
                if len(current_batch) >= BATCH_SIZE:
                    active_plan_index = _run_batch_with_ranked_plans(
                        ranked_plans,
                        active_plan_index,
                        current_batch,
                        batch_id,
                        WORKERS,
                        FULL_INPUT_HDF5,
                        current_checksum,
                        current_model_name,
                        current_saving_mode,
                        current_gap_penalties,
                    )
                    batch_id += 1
                    current_batch = []
                    pbar.update(1)

        if len(current_batch) > 0:
            active_plan_index = _run_batch_with_ranked_plans(
                ranked_plans,
                active_plan_index,
                current_batch,
                batch_id,
                WORKERS,
                FULL_INPUT_HDF5,
                current_checksum,
                current_model_name,
                current_saving_mode,
                current_gap_penalties,
            )
            pbar.update(1)
            
        pbar.close()
    elif cached_precision is not None:
        active_matmul_precision = cached_precision
    elif precision_setting == "tf32":
        active_matmul_precision = "tf32"
    else:
        active_matmul_precision = "ieee_fp32"

    # Compile intermediate HDF5 batches into final output
    compile_final_output(
        headers,
        seq_lens,
        required_mask,
        n,
        current_checksum,
        current_model_name,
        current_saving_mode,
        current_gap_penalties,
        active_matmul_precision,
    )

def main(argv=None):
    load_tool_settings(globals(), __file__, PROJECT_ROOT, argv)
    run_job_distributor()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
