# Copyright 2026 Xuebin Feng
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
File: Align_Similarity_Matrix.py
===================================
Description:
This script computes an all-vs-all sequence similarity matrix utilizing protein embeddings instead of traditional sequence 
characters. It performs alignment scoring using dynamic programming on distance matrices derived from the embeddings.

Input:
- HDF5 dataset containing sequence embeddings generated by models like ESM (`{SEQUENCE_SET}_{MODEL_NAME}_embeddings.h5`).

Output:
- A network edge HDF5 file containing pairwise combinations (i, j), raw local/global scores, and alignment lengths (`{SEQUENCE_SET}_{MODEL_NAME}_network.h5`).

Settings:
- SEQUENCE_SET: The base name of the project.
- MODEL_NAME: The name of the embedding model used.
- WORKERS: Number of multiprocessing workers to use.
- HOST_CACHE_GB: Automatic or explicit host-RAM cap for packed embeddings.
- EXECUTION_MODE: Automatic, scalar, or tiled pairwise score execution.
- ACCELERATOR_PRECISION: Validated automatic, IEEE FP32, or NVIDIA TF32 matmul.
- LOCAL_GAP_P: The gap penalty for local alignment (e.g. Smith-Waterman style).
- GLOBAL_GAP_P: The gap penalty for global alignment (e.g. Needleman-Wunsch style).

Algorithm:
1. Packs the embedding database in bounded host RAM when possible; otherwise
   loads byte-bounded sequence tiles from HDF5.
2. Tunes lanes on a short cost-stratified sample, then confirms the selected
   scalar and padded-batched accelerator plans on production-ordered pairs.
3. Passes those matrices by reference through a bounded queue to parallel CPU
   threads, which evaluate Global and Local Alignments using Numba functions
   compiled to release the Python GIL.
4. On CPU-only systems, distributes complete pairs across the CPU workers.
5. Streams canonical results into one checkpointed HDF5 partial file and
   atomically publishes it when complete.
"""
# %% Import Necessary Libraries
# Limit threads to prevent CPU thrashing
import os
try:
    from tools import _bootstrap
except ModuleNotFoundError:
    import _bootstrap
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

import pickle
import numpy as np
import torch
import math
import sys
import h5py
import hashlib
import threading
import time
from collections import deque
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from contextlib import nullcontext
from multiprocessing import Pool, set_start_method
from tqdm import tqdm
from utilities import Hardware_Utils
from utilities.Embedding_Alignment_Engine import (
    AcceleratorMemoryPlan,
    CompactPairTasks,
    TiledAcceleratorSession,
    EmbeddingTileStore,
    accelerator_memory_plan,
    benchmark_accelerator_execution_plans,
    compare_precision_results,
    cuda_matmul_precision,
    estimate_accelerator_working_set,
    get_accelerator_backend,
    is_nvidia_cuda,
    measure_accelerator_session,
    normalize_execution_mode,
    normalize_precision_setting,
    run_tiled_accelerator_pipeline,
    tiled_accelerator_support,
)
from utilities.Alignment_Score_Kernels import (
    GlobalLocalScratch,
    global_local_scores,
)
from utilities.Embedding_HDF5 import read_embedding_manifest
from utilities.Alignment_Network_HDF5 import (
    AlignmentNetworkIdentity,
    CanonicalAlignmentNetworkReader,
    ResumableAlignmentNetworkWriter,
    SparsityProfile,
    backup_incompatible_target,
    build_sparsity_profile,
    completed_target_matches,
    discover_compatible_alignment_networks,
    iter_mask_pairs,
    make_selection_fingerprint,
)

# ==========================================
# CONFIGURATION
# ==========================================
INPUT_HDF5 = None
EDGE_PREFILTERING = False
PREFILTER_STRENGTH = 20
POOLING_METHOD = "max"    # ("mean", "max") - method to pool residue embeddings into sequence vectors
LENGTH_RATIO_POWER = 2.0  # (float) - exponent to scale the sequence length ratio penalty
WORKERS = 12
DEVICE_SELECTION = "auto"
EXECUTION_MODE = "auto"
ACCELERATOR_TUNE_PAIRS = 256
ACCELERATOR_CONFIRM_PAIRS = 2048
HOST_CACHE_GB = "auto"
ACCELERATOR_PRECISION = "auto"
# Compatibility for callers that use _accelerator_worker_count directly.
# Production scheduling always uses the automatic lane tuner.
GPU_STREAMS = 4
LOCAL_GAP_P = -2.0
GLOBAL_GAP_P = 0.0
BATCH_SIZE = 500000

from utilities.Tool_Directories import project_directory_defaults
from utilities.Tool_Settings import inherited_settings_path, load_tool_settings

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
_DEFAULT_DIRECTORIES = project_directory_defaults(PROJECT_ROOT)
EMBED_DIR = _DEFAULT_DIRECTORIES["EMBED_DIR"]
NETWORK_DIR = _DEFAULT_DIRECTORIES["NETWORK_DIR"]

# --- JSON Settings Override ---
import json
import ast
import os

# Automatically calculate the root directory of the SSN project for the current PC
# (Tool scripts are located in the /tools/ folder)
SETTINGS_FILE = inherited_settings_path(__file__) or os.path.join(PROJECT_ROOT, "Input_Files", "tools_settings.json")

if __name__ != "__main__" and os.path.exists(SETTINGS_FILE):
    try:
        with open(SETTINGS_FILE, "r", encoding="utf-8") as f:
            all_settings = json.load(f)
            
            # 1. Load GLOBAL directories and convert relative paths to absolute paths
            if "DIRECTORIES" in all_settings:
                for k, v in all_settings["DIRECTORIES"].items():
                    if k in globals() and v is not None and str(v).strip() != "":
                        # Expand relative paths dynamically based on the current PC
                        if not os.path.isabs(str(v)):
                            v = os.path.normpath(os.path.join(PROJECT_ROOT, str(v)))
                        globals()[k] = v
                        
            # 2. Load script-specific settings
            script_name = os.path.basename(__file__)
            if script_name in all_settings:
                user_settings = all_settings[script_name]
                for k, v in user_settings.items():
                    if k in globals() and v is not None and str(v).strip() != "":
                        orig = globals()[k]
                        
                        # Type casting to match the original Python variable type
                        if isinstance(orig, int) and not isinstance(orig, bool):
                            try: v = int(v)
                            except: pass
                        elif isinstance(orig, float):
                            try: v = float(v)
                            except: pass
                        elif isinstance(orig, list):
                            try: v = ast.literal_eval(v) if isinstance(v, str) else v
                            except: pass
                        elif orig is None:
                            if v == "None": v = None
                            elif str(v).replace('.', '', 1).isdigit():
                                v = float(v) if '.' in str(v) else int(v)
                                
                        # Convert any script-specific directory paths to absolute paths
                        if isinstance(v, str) and k.endswith("_DIR") and not os.path.isabs(v):
                            v = os.path.normpath(os.path.join(PROJECT_ROOT, v))
                            
                        globals()[k] = v
    except Exception as e:
        print(f"Failed to load user settings: {e}")

import re
MODEL_NAME = "unknown"
SEQUENCE_SET = ""
FULL_INPUT_HDF5 = None
FINAL_OUTPUT_NET = None
active_matmul_precision = "ieee_fp32"
active_embedding_store = None
active_sequence_lengths = None


def _sparsity_filename_token(value):
    value = float(value)
    token = f"{value:g}"
    return token.replace("-", "m").replace(".", "p")


def configure_runtime_paths():
    """Resolve GUI-selected paths immediately before starting the job."""
    global MODEL_NAME, SEQUENCE_SET
    global FULL_INPUT_HDF5, FINAL_OUTPUT_NET

    if INPUT_HDF5 is None or not str(INPUT_HDF5).strip():
        raise ValueError("No embeddings file has been selected.")

    selected_path = os.fspath(INPUT_HDF5)
    filename = os.path.basename(selected_path)
    base_name = filename.replace("_embeddings.h5", "").replace(".h5", "")

    MODEL_NAME = "unknown"
    SEQUENCE_SET = base_name
    match = re.search(r"^(.*)_\[(.*)\]_embeddings\.h5$", filename)
    if match:
        SEQUENCE_SET = match.group(1)
        MODEL_NAME = match.group(2)

    FULL_INPUT_HDF5 = (
        os.path.normpath(selected_path)
        if os.path.isabs(selected_path)
        else os.path.normpath(os.path.join(EMBED_DIR, selected_path))
    )
    if EDGE_PREFILTERING and float(PREFILTER_STRENGTH) > 0.0:
        sparse_suffix = _sparsity_filename_token(PREFILTER_STRENGTH)
        output_name = (
            f"{SEQUENCE_SET}_[{MODEL_NAME}]_network_"
            f"sparse{sparse_suffix}pct.h5"
        )
    else:
        output_name = f"{SEQUENCE_SET}_[{MODEL_NAME}]_network.h5"
    FINAL_OUTPUT_NET = os.path.join(NETWORK_DIR, output_name)
        
# %% =======================================
# KERNELS
# ==========================================
def calculate_file_hash(file_path):
    """
    Computes the MD5 checksum of a file in chunks to verify consistency.
    """
    hasher = hashlib.md5()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


class EmbeddingFileError(RuntimeError):
    """Raised when an embedding HDF5 file is incomplete or incompatible."""


def load_embedding_metadata(file_path):
    """
    Validate an embedding database using Embedding_HDF5.read_embedding_manifest
    and return ordered headers, safe headers, and sequence lengths.
    """
    try:
        with h5py.File(file_path, "r") as hf:
            manifest = read_embedding_manifest(
                hf,
                require_complete=True,
                validate_embeddings=True,
            )
            headers = manifest.headers
            safe_headers = [
                header.replace("/", "_").replace("\\", "_")
                for header in headers
            ]
            seq_lens = [len(seq) for seq in manifest.sequences]
    except EmbeddingFileError:
        raise
    except Exception as error:
        raise EmbeddingFileError(
            f"Embedding file '{file_path}' validation failed: {error}"
        ) from error

    return headers, safe_headers, seq_lens, manifest


def _device_cache_key(device):
    """Return a stable key for per-backend scoring capability caches."""
    return (_device_type(device), getattr(device, "index", None))


def _normalize_embedding_torch(embedding, device):
    """Transfer one embedding to ``device`` and L2-normalize its residues."""
    tensor = torch.as_tensor(embedding, device=device, dtype=torch.float32)
    return torch.nn.functional.normalize(tensor, p=2, dim=-1)


def _normalized_row_for_active_lane(emb_i, device):
    """
    Return the normalized left embedding for the active accelerator lane.

    ``_compute_accelerated_matrix`` supplies a row key while it owns the lane.
    The cached tensor therefore remains on the same worker thread and stream
    that created it. Direct callers, including the CPU-only process fallback,
    do not have an active row key and retain the original per-pair behavior.
    """
    active_row_key = getattr(accelerator_thread_state, "active_row_key", None)
    if active_row_key is None:
        return _normalize_embedding_torch(emb_i, device)

    cached_row_key = getattr(accelerator_thread_state, "normalized_row_key", None)
    if cached_row_key != active_row_key:
        accelerator_thread_state.normalized_row = _normalize_embedding_torch(
            emb_i,
            device,
        )
        accelerator_thread_state.normalized_row_key = active_row_key
    return accelerator_thread_state.normalized_row


std_mean_support_cache = {}


def _score_matrix_statistics(sim_mat, device):
    """Return row/column means and standard deviations with safe fallback."""
    cache_key = _device_cache_key(device)
    fused_supported = std_mean_support_cache.get(cache_key)

    if fused_supported is not False:
        try:
            row_std, row_mean = torch.std_mean(
                sim_mat,
                dim=1,
                keepdim=True,
                correction=0,
            )
            col_std, col_mean = torch.std_mean(
                sim_mat,
                dim=0,
                keepdim=True,
                correction=0,
            )
        except (RuntimeError, NotImplementedError):
            # Some accelerator integrations do not implement std_mean. Only
            # remember the failure after the established operations succeed,
            # so unrelated failures are not silently cached as capabilities.
            row_mean = sim_mat.mean(dim=1, keepdim=True)
            row_std = sim_mat.std(dim=1, keepdim=True, correction=0)
            col_mean = sim_mat.mean(dim=0, keepdim=True)
            col_std = sim_mat.std(dim=0, keepdim=True, correction=0)
            std_mean_support_cache[cache_key] = False
        else:
            if fused_supported is None:
                std_mean_support_cache[cache_key] = True
    else:
        row_mean = sim_mat.mean(dim=1, keepdim=True)
        row_std = sim_mat.std(dim=1, keepdim=True, correction=0)
        col_mean = sim_mat.mean(dim=0, keepdim=True)
        col_std = sim_mat.std(dim=0, keepdim=True, correction=0)

    return row_mean, row_std, col_mean, col_std


def _score_matrix_from_normalized_row(t_i_norm, emb_j, device):
    """Calculate a score matrix when the left embedding is pre-normalized."""
    t_j_norm = _normalize_embedding_torch(emb_j, device)
    cos_sim = torch.mm(t_i_norm, t_j_norm.T).clamp(-1.0, 1.0)
    dist_mat = 1.0 - cos_sim
    sim_mat = torch.exp(-dist_mat)

    epsilon = 1e-8
    row_mean, row_std, col_mean, col_std = _score_matrix_statistics(
        sim_mat,
        device,
    )

    z_r = (sim_mat - row_mean) / (row_std + epsilon)
    z_c = (sim_mat - col_mean) / (col_std + epsilon)
    final_score = (z_r + z_c) / 2.0

    return final_score.to(dtype=torch.float32, device="cpu").numpy()


def compute_score_matrix_torch(emb_i, emb_j, device):
    t_i_norm = _normalized_row_for_active_lane(emb_i, device)
    return _score_matrix_from_normalized_row(t_i_norm, emb_j, device)

# %% =======================================
# HDF5 WORKER INITIALIZATION
# ==========================================
worker_hf = None
worker_device = None
alignment_scratch_state = threading.local()

def init_worker(h5_path):
    global worker_hf, worker_device
    worker_hf = h5py.File(h5_path, "r", libver='latest', swmr=True)
    # This initializer is used only by the CPU-only fallback. Keeping the
    # device explicit prevents child processes from creating GPU contexts.
    worker_device = torch.device("cpu")

# %% =======================================
# CPU ALIGNMENT WORKERS
# ==========================================
def calculate_alignment_data(args):
    """
    Run the dynamic-programming portion of one pair entirely on the CPU.

    The score matrix is produced by the single accelerator-owning thread and
    passed by reference to a CPU worker thread. The Numba kernels release the
    GIL, so multiple alignments can execute on separate CPU cores.
    """
    idx_i, idx_j, matrix = args

    scratch = getattr(alignment_scratch_state, "scratch", None)
    if scratch is None:
        scratch = GlobalLocalScratch()
        alignment_scratch_state.scratch = scratch
    (g_raw, g_len, l_raw, l_len), _grew = scratch.score(
        matrix,
        GLOBAL_GAP_P,
        LOCAL_GAP_P,
    )

    return (idx_i, idx_j, l_raw, l_len, g_raw, g_len)


def calculate_alignment_chunk(items):
    """Finish a bounded packet chunk with one grow-only thread scratch."""
    scratch = getattr(alignment_scratch_state, "scratch", None)
    if scratch is None:
        scratch = GlobalLocalScratch()
        alignment_scratch_state.scratch = scratch
    results = []
    growths = 0
    for ordinal, idx_i, idx_j, matrix in items:
        (g_raw, g_len, l_raw, l_len), grew = scratch.score(
            matrix,
            GLOBAL_GAP_P,
            LOCAL_GAP_P,
        )
        growths += int(grew)
        results.append(
            (ordinal, (idx_i, idx_j, l_raw, l_len, g_raw, g_len))
        )
    return results, growths


def calculate_cpu_pair(args):
    """
    CPU-only fallback that computes both the score matrix and alignments.

    Multiple processes may execute this function because none of them creates
    or accesses an accelerator context.
    """
    idx_i, idx_j, header_i, header_j = args
    global worker_hf, worker_device

    emb_i = worker_hf["embeddings"][header_i][:]
    emb_j = worker_hf["embeddings"][header_j][:]
    matrix = compute_score_matrix_torch(emb_i, emb_j, worker_device)

    return calculate_alignment_data((idx_i, idx_j, matrix))


def _uses_accelerator(device):
    return getattr(device, "type", str(device).split(":", 1)[0]) != "cpu"


accelerator_thread_state = threading.local()
accelerator_lane_cache = {}


def _device_type(device):
    """Return a normalized PyTorch device type."""
    return getattr(device, "type", str(device).split(":", 1)[0])


def _supports_explicit_streams(device):
    """Return whether this backend exposes usable Python stream controls."""
    return _device_type(device) in {"cuda", "xpu"}


def _accelerator_worker_count(device, cpu_workers, requested_lanes=None):
    """
    Bound an explicit lane request to what the selected backend can use.

    ``requested_lanes`` is optional to preserve compatibility with callers of
    the previous CUDA-only helper.
    """
    if not _supports_explicit_streams(device):
        return 1
    if requested_lanes is None:
        requested_lanes = GPU_STREAMS
    return max(1, min(int(requested_lanes), int(cpu_workers)))


def _accelerator_lane_candidates(device, cpu_workers):
    """Return conservative tuning candidates for the active backend."""
    device_type = _device_type(device)
    max_lanes = max(1, int(cpu_workers))

    if device_type == "cuda":
        candidates = [1, 2, 4, 8, 16]
        backend_cap = 16
    elif device_type == "xpu":
        candidates = [1, 2, 4]
        backend_cap = 4
    else:
        return [1]

    limit = min(max_lanes, backend_cap)
    bounded = [count for count in candidates if count <= limit]
    if limit not in bounded:
        bounded.append(limit)
    return sorted(set(bounded))


def _accelerator_name(device):
    """Return a stable device label for tuning messages and cache keys."""
    device_type = _device_type(device)
    try:
        if device_type == "cuda":
            return torch.cuda.get_device_name(device)
        if device_type == "xpu":
            return torch.xpu.get_device_name(device)
        if device_type == "mps" and hasattr(torch.backends.mps, "get_name"):
            return torch.backends.mps.get_name()
    except (AttributeError, RuntimeError):
        pass
    return str(device)


def _stream_context(device):
    """
    Return a context for a stream owned by the current accelerator thread.

    CUDA and XPU use separate explicit streams. MPS and other
    backends deliberately retain their default execution queue.
    """
    device_type = _device_type(device)
    if device_type == "cuda":
        backend = torch.cuda
    elif device_type == "xpu":
        backend = torch.xpu
    else:
        return nullcontext()

    stream = getattr(accelerator_thread_state, "stream", None)
    stream_key = getattr(accelerator_thread_state, "stream_key", None)
    current_key = (device_type, str(device))
    if stream is None or stream_key != current_key:
        stream = backend.Stream(device=device)
        accelerator_thread_state.stream = stream
        accelerator_thread_state.stream_key = current_key

    return _DeviceStreamContext(backend, device, stream)


class _DeviceStreamContext:
    """Enter matching device and stream contexts for CUDA or XPU."""

    def __init__(self, backend, device, stream):
        self.device_context = backend.device(device)
        self.stream_context = backend.stream(stream)

    def __enter__(self):
        self.device_context.__enter__()
        try:
            return self.stream_context.__enter__()
        except BaseException:
            self.device_context.__exit__(*sys.exc_info())
            raise

    def __exit__(self, exc_type, exc_value, traceback):
        try:
            return self.stream_context.__exit__(
                exc_type,
                exc_value,
                traceback,
            )
        finally:
            self.device_context.__exit__(exc_type, exc_value, traceback)


def _compute_accelerated_matrix(args):
    """
    Compute one score matrix on a stream owned by the current worker thread.

    All threads share one accelerator process. CUDA and XPU threads own
    separate streams; backends without public stream controls use one lane.
    """
    idx_i, idx_j, emb_i, emb_j, device = args
    with torch.inference_mode():
        with _stream_context(device):
            previous_row_key = getattr(
                accelerator_thread_state,
                "active_row_key",
                None,
            )
            accelerator_thread_state.active_row_key = (
                _device_cache_key(device),
                idx_i,
            )
            try:
                matrix = compute_score_matrix_torch(emb_i, emb_j, device)
            finally:
                if previous_row_key is None:
                    try:
                        del accelerator_thread_state.active_row_key
                    except AttributeError:
                        pass
                else:
                    accelerator_thread_state.active_row_key = previous_row_key

    return idx_i, idx_j, matrix


def _run_scalar_accelerated_pipeline(
    batch_tasks,
    workers,
    input_h5,
    device,
    batch_id,
    accelerator_workers,
    show_progress,
    result_callback=None,
    result_chunk_size=65536,
):
    """
    Run one complete accelerator/CPU pipeline with a fixed lane count.

    GPU and CPU queues are independently bounded. Matrices stay in the same
    process and are passed by reference, avoiding serialization and extra CUDA
    contexts while allowing both stages to remain busy.
    """
    results = []
    gpu_pending = set()
    cpu_pending = set()
    ready_for_cpu = deque()
    ready_limit = max(accelerator_workers, min(workers, 8))
    task_iterator = iter(batch_tasks)
    tasks_exhausted = False
    cached_row_header = None
    cached_row_embedding = None
    progress_context = (
        tqdm(
            total=len(batch_tasks),
            desc=(
                f"  Batch {batch_id} "
                f"({accelerator_workers} accelerator lane"
                f"{'s' if accelerator_workers != 1 else ''})"
            ),
            leave=False,
        )
        if show_progress
        else nullcontext(None)
    )

    with h5py.File(input_h5, "r", libver="latest", swmr=True) as hf, \
            ThreadPoolExecutor(
                max_workers=accelerator_workers,
                thread_name_prefix="alignment-gpu",
            ) as gpu_executor, \
            ThreadPoolExecutor(
                max_workers=workers,
                thread_name_prefix="alignment-cpu",
            ) as cpu_executor, \
            progress_context as progress:
        while (
            not tasks_exhausted
            or gpu_pending
            or ready_for_cpu
            or cpu_pending
        ):
            # Move completed matrices into the independently bounded CPU pool.
            while ready_for_cpu and len(cpu_pending) < workers:
                cpu_pending.add(
                    cpu_executor.submit(
                        calculate_alignment_data,
                        ready_for_cpu.popleft(),
                    )
                )

            # Keep every CUDA stream supplied, but do not accumulate an
            # unbounded number of embeddings or score matrices in host RAM.
            while (
                not tasks_exhausted
                and len(gpu_pending) < accelerator_workers
                and len(ready_for_cpu) + len(gpu_pending) < ready_limit
            ):
                try:
                    idx_i, idx_j, header_i, header_j = next(task_iterator)
                except StopIteration:
                    tasks_exhausted = True
                    break

                # Tasks are generated row-by-row. Reuse the row embedding
                # instead of reading it from HDF5 once for every pair.
                if header_i != cached_row_header:
                    cached_row_embedding = hf["embeddings"][header_i][:]
                    cached_row_header = header_i
                emb_i = cached_row_embedding
                emb_j = hf["embeddings"][header_j][:]
                gpu_pending.add(
                    gpu_executor.submit(
                        _compute_accelerated_matrix,
                        (
                            idx_i,
                            idx_j,
                            emb_i,
                            emb_j,
                            device,
                        ),
                    )
                )

            completed_gpu = {
                future for future in gpu_pending if future.done()
            }
            completed_cpu = {
                future for future in cpu_pending if future.done()
            }

            if not completed_gpu and not completed_cpu:
                all_pending = gpu_pending | cpu_pending
                if not all_pending:
                    continue
                completed, _ = wait(
                    all_pending,
                    return_when=FIRST_COMPLETED,
                )
                completed_gpu = completed & gpu_pending
                completed_cpu = completed & cpu_pending

            for future in completed_gpu:
                gpu_pending.remove(future)
                ready_for_cpu.append(future.result())

            for future in completed_cpu:
                cpu_pending.remove(future)
                results.append(future.result())
                if progress is not None:
                    progress.update(1)
                if (
                    result_callback is not None
                    and len(results) >= int(result_chunk_size)
                ):
                    result_callback(results)
                    results.clear()

    if result_callback is not None and results:
        result_callback(results)
        results.clear()
    return results


def _run_accelerated_pipeline(
    batch_tasks,
    workers,
    input_h5,
    device,
    batch_id,
    accelerator_workers,
    show_progress,
    matmul_precision="ieee_fp32",
    result_callback=None,
):
    """Compatibility wrapper for the original per-pair accelerator path."""
    with cuda_matmul_precision(matmul_precision):
        return _run_scalar_accelerated_pipeline(
            batch_tasks,
            workers,
            input_h5,
            device,
            batch_id,
            accelerator_workers,
            show_progress,
            result_callback=result_callback,
        )


def _select_accelerator_lanes(
    batch_tasks,
    workers,
    input_h5,
    device,
    batch_id,
    matmul_precision=None,
):
    """
    Select accelerator concurrency using a short representative benchmark.

    The benchmark includes HDF5 input, accelerator work, the device-to-host
    transfer, and CPU alignment. This optimizes completed-pair throughput
    rather than accelerator utilization alone.
    """
    candidates = _accelerator_lane_candidates(device, workers)
    if matmul_precision is None:
        matmul_precision = active_matmul_precision
    if len(candidates) == 1 or len(batch_tasks) < 2:
        return 1

    cache_key = (
        _device_type(device),
        _accelerator_name(device),
        int(workers),
    )
    if cache_key in accelerator_lane_cache:
        return accelerator_lane_cache[cache_key]

    tune_count = max(
        2,
        min(int(ACCELERATOR_TUNE_PAIRS), len(batch_tasks)),
    )
    tuning_tasks = list(batch_tasks[:tune_count])
    device_name = cache_key[1]
    print(
        f"  > Auto-tuning accelerator lanes on {device_name} "
        f"using {tune_count} representative pairs..."
    )

    # Warm the backend, HDF5 cache, PyTorch allocators, and Numba kernels
    # before recording any candidate.
    _run_accelerated_pipeline(
        tuning_tasks,
        workers,
        input_h5,
        device,
        batch_id,
        accelerator_workers=1,
        show_progress=False,
        matmul_precision=matmul_precision,
    )

    measured_rates = {}
    for lanes in candidates:
        start_time = time.perf_counter()
        try:
            _run_accelerated_pipeline(
                tuning_tasks,
                workers,
                input_h5,
                device,
                batch_id,
                accelerator_workers=lanes,
                show_progress=False,
                matmul_precision=matmul_precision,
            )
        except (RuntimeError, NotImplementedError) as error:
            if lanes == 1:
                raise
            print(
                f"    {lanes} lanes unavailable: "
                f"{type(error).__name__}: {error}"
            )
            continue

        elapsed = max(time.perf_counter() - start_time, 1e-9)
        measured_rates[lanes] = tune_count / elapsed

    if not measured_rates:
        selected = 1
    else:
        fastest_rate = max(measured_rates.values())
        # Prefer the least concurrency within 3% of the fastest result. This
        # avoids extra memory use for differences smaller than tuning noise.
        selected = min(
            lanes
            for lanes, rate in measured_rates.items()
            if rate >= fastest_rate * 0.97
        )

    accelerator_lane_cache[cache_key] = selected
    measurements = ", ".join(
        f"{lanes}: {rate:.1f} pairs/s"
        for lanes, rate in sorted(measured_rates.items())
    )
    print(f"    {measurements}")
    print(f"  > Selected {selected} accelerator lane(s).")
    return selected


def process_accelerated_tasks(
    batch_tasks,
    workers,
    input_h5,
    device,
    batch_id,
    accelerator_workers=None,
    embedding_store=None,
    sequence_lengths=None,
    matmul_precision="ieee_fp32",
    execution_variant="scalar",
    result_callback=None,
    tiled_session=None,
    show_progress=True,
):
    """
    Auto-select accelerator concurrency, then run the complete task batch.
    """
    if accelerator_workers is None:
        accelerator_workers = _select_accelerator_lanes(
            batch_tasks,
            workers,
            input_h5,
            device,
            batch_id,
            matmul_precision=matmul_precision,
        )
    if (
        execution_variant == "tiled"
        and _device_type(device) in {"cuda", "xpu"}
        and embedding_store is not None
        and sequence_lengths is not None
    ):
        backend = get_accelerator_backend(device)
        progress = tqdm(
            total=len(batch_tasks),
            desc=(
                f"  Batch {batch_id} (tiled {_device_type(device).upper()}, "
                f"{accelerator_workers} lane"
                f"{'s' if accelerator_workers != 1 else ''})"
            ),
            leave=False,
            disable=not show_progress,
        )
        matrix_budget = None
        try:
            for attempt in range(4):
                checkpoint = (
                    result_callback.checkpoint()
                    if result_callback is not None
                    and hasattr(result_callback, "checkpoint")
                    else None
                )
                progress_checkpoint = getattr(progress, "n", None)
                try:
                    return run_tiled_accelerator_pipeline(
                        batch_tasks,
                        store=embedding_store,
                        lengths=sequence_lengths,
                        device=device,
                        workers=workers,
                        lanes=accelerator_workers,
                        alignment_callback=calculate_alignment_data,
                        alignment_chunk_callback=calculate_alignment_chunk,
                        precision=matmul_precision,
                        progress=progress,
                        matrix_budget_override=matrix_budget,
                        result_callback=result_callback,
                        session=tiled_session,
                    )
                except Exception as error:
                    if not backend.is_out_of_memory(error):
                        raise
                    if checkpoint is not None:
                        result_callback.rollback(checkpoint)
                    if (
                        isinstance(progress_checkpoint, (int, np.integer))
                        and isinstance(getattr(progress, "n", None), (int, np.integer))
                    ):
                        progress.update(progress_checkpoint - progress.n)
                    if tiled_session is not None:
                        matrix_budget = tiled_session.recover_from_oom(
                            minimum_budget=16 * 1024 * 1024
                        )
                    else:
                        backend.empty_cache()
                        default_budget = accelerator_memory_plan(
                            device, lanes=accelerator_workers
                        ).matrix_pool_bytes
                        matrix_budget = max(
                            16 * 1024 * 1024,
                            int(matrix_budget or default_budget) // 2,
                        )
                    print(
                        f"  > {_device_type(device).upper()} memory pressure; "
                        f"retrying batch with "
                        f"{matrix_budget / (1024 ** 2):.0f} MiB shared "
                        f"matrix budget."
                    )
            raise RuntimeError(
                "Tiled accelerator execution remained out of memory after "
                "four retries; the batch must use the next ranked plan."
            )
        finally:
            progress.close()
    return _run_accelerated_pipeline(
        batch_tasks,
        workers,
        input_h5,
        device,
        batch_id,
        accelerator_workers,
        show_progress=show_progress,
        matmul_precision=matmul_precision,
        result_callback=result_callback,
    )


def process_cpu_tasks(
    batch_tasks,
    workers,
    input_h5,
    batch_id,
    show_progress=True,
    result_callback=None,
):
    """Process complete pairs in parallel when no accelerator is available."""
    results = []
    with Pool(
        processes=workers,
        initializer=init_worker,
        initargs=(input_h5,),
    ) as pool:
        iterator = pool.imap_unordered(
            calculate_cpu_pair,
            batch_tasks,
            chunksize=10,
        )
        progress = tqdm(
            iterator,
            total=len(batch_tasks),
            desc=f"  Batch {batch_id}",
            leave=False,
            disable=not show_progress,
        )
        for result in progress:
            results.append(result)
            if result_callback is not None and len(results) >= 65536:
                result_callback(results)
                results.clear()
    if result_callback is not None and results:
        result_callback(results)
        results.clear()
    return results


def _representative_alignment_tasks(batch_tasks, input_h5, limit):
    """Select a deterministic, cost-stratified subset of pending pairs."""
    if len(batch_tasks) <= limit:
        return list(batch_tasks)
    probe_count = min(len(batch_tasks), max(int(limit) * 8, int(limit)))
    probe_indices = np.linspace(
        0, len(batch_tasks) - 1, num=probe_count, dtype=np.int64
    )
    probes = [batch_tasks[int(index)] for index in probe_indices]
    with h5py.File(input_h5, "r", libver="latest", swmr=True) as hf:
        scored = []
        for task in probes:
            _, _, header_i, header_j = task
            shape_i = hf["embeddings"][header_i].shape
            shape_j = hf["embeddings"][header_j].shape
            feature_dim = shape_i[1] if len(shape_i) > 1 else 1
            scored.append((shape_i[0] * shape_j[0] * feature_dim, task))
    scored.sort(key=lambda item: item[0])
    selected_indices = np.linspace(
        0, len(scored) - 1, num=min(int(limit), len(scored)), dtype=np.int64
    )
    return [scored[int(index)][1] for index in selected_indices]


def _representative_pending_pairs(
    safe_headers,
    sequence_lengths,
    computed_mask,
    required_mask,
    num_tasks,
    limit,
):
    """Sample the complete pending workload, then stratify by estimated cost."""
    limit = max(1, min(int(limit), int(num_tasks)))
    probe_count = min(int(num_tasks), max(limit * 8, limit))
    target_ordinals = np.linspace(
        0, int(num_tasks) - 1, num=probe_count, dtype=np.int64
    )
    targets = set(int(value) for value in target_ordinals)
    probes = []
    ordinal = 0
    n_sequences = len(safe_headers)
    for row in range(n_sequences):
        columns = np.arange(row + 1, n_sequences)
        pending = ~computed_mask[row, row + 1:]
        if required_mask is not None:
            pending &= required_mask[row, row + 1:]
        for column in columns[pending]:
            if ordinal in targets:
                cost = int(sequence_lengths[row]) * int(sequence_lengths[column])
                probes.append(
                    (
                        cost,
                        (
                            row,
                            int(column),
                            safe_headers[row],
                            safe_headers[column],
                        ),
                    )
                )
            ordinal += 1

    probes.sort(key=lambda item: (item[0], item[1][0], item[1][1]))
    selected_indices = np.linspace(
        0, len(probes) - 1, num=min(limit, len(probes)), dtype=np.int64
    )
    return [probes[int(index)][1] for index in selected_indices]


def _first_pending_pairs(
    safe_headers,
    computed_mask,
    required_mask,
    num_tasks,
    limit,
):
    """Return the first production-ordered pending pairs for confirmation."""
    limit = max(1, min(int(limit), int(num_tasks)))
    sample = []
    n_sequences = len(safe_headers)
    for row in range(n_sequences - 1):
        pending = ~computed_mask[row, row + 1:]
        if required_mask is not None:
            pending &= required_mask[row, row + 1:]
        columns = np.flatnonzero(pending) + row + 1
        for column in columns:
            column = int(column)
            sample.append(
                (row, column, safe_headers[row], safe_headers[column])
            )
            if len(sample) >= limit:
                return sample
    return sample


def _representative_row_local_pending_pairs(
    safe_headers,
    sequence_lengths,
    computed_mask,
    required_mask,
    num_tasks,
    limit,
):
    """Return a cost-stratified sample that retains production row locality."""
    limit = max(1, min(int(limit), int(num_tasks)))
    n_sequences = len(safe_headers)
    populated_rows = []
    pending_by_row = {}
    for row in range(n_sequences - 1):
        pending = ~computed_mask[row, row + 1:]
        if required_mask is not None:
            pending &= required_mask[row, row + 1:]
        columns = np.flatnonzero(pending) + row + 1
        if len(columns):
            populated_rows.append(row)
            pending_by_row[row] = columns
    if not populated_rows:
        return []

    row_count = min(8, len(populated_rows), limit)
    row_positions = np.linspace(
        0,
        len(populated_rows) - 1,
        num=row_count,
        dtype=np.int64,
    )
    selected_rows = [populated_rows[int(position)] for position in row_positions]
    per_row = max(1, math.ceil(limit / len(selected_rows)))
    sample = []
    for row in selected_rows:
        columns = pending_by_row[row]
        ordered = sorted(
            (int(column) for column in columns),
            key=lambda column: (
                int(sequence_lengths[row]) * int(sequence_lengths[column]),
                column,
            ),
        )
        positions = np.linspace(
            0,
            len(ordered) - 1,
            num=min(per_row, len(ordered)),
            dtype=np.int64,
        )
        for position in positions:
            column = ordered[int(position)]
            sample.append(
                (row, column, safe_headers[row], safe_headers[column])
            )
    return sample[:limit]


def _precision_device(candidates):
    manual = Hardware_Utils.resolve_device_selection(DEVICE_SELECTION, candidates)
    if manual is not None:
        return manual if manual.backend == "cuda" else None
    return next((candidate for candidate in candidates if candidate.backend == "cuda"), None)


def _execution_variants(candidate):
    """Return execution variants allowed for one hardware candidate."""
    mode = normalize_execution_mode(EXECUTION_MODE)
    tiled_supported = (
        candidate.backend in {"cuda", "xpu"}
        and tiled_accelerator_support(
            candidate.device, require_memory=False
        )[0]
    )
    if mode == "scalar":
        return ["scalar"]
    if mode == "tiled":
        return ["tiled"] if tiled_supported else []
    variants = ["scalar"]
    if tiled_supported:
        variants.append("tiled")
    return variants


def _validate_execution_mode_hardware():
    """Fail early when a forced execution mode cannot use selected hardware."""
    mode = normalize_execution_mode(EXECUTION_MODE)
    if mode != "tiled":
        return mode
    candidates = Hardware_Utils.get_available_devices()
    manual = Hardware_Utils.resolve_device_selection(
        DEVICE_SELECTION, candidates
    )
    if manual is not None and not _execution_variants(manual):
        raise ValueError(
            "Tiled execution requires a stream-capable CUDA/ROCm or XPU "
            "accelerator; the selected device "
            f"is '{manual.spec}'."
        )
    eligible = [
        candidate for candidate in candidates
        if _execution_variants(candidate) == ["tiled"]
    ]
    if manual is not None:
        eligible = [manual]
    if not eligible:
        raise ValueError(
            "Tiled execution was requested, but no compatible CUDA/ROCm or "
            "XPU accelerator is available."
        )
    return mode


def _gib_text(byte_count):
    return f"{int(byte_count) / (1024 ** 3):.2f} GiB"


def _device_memory_estimate_text(estimate):
    return (
        f"projected {_gib_text(estimate.projected_peak_bytes)} / "
        f"safe {_gib_text(estimate.safe_peak_bytes)}; "
        f"tile {_gib_text(estimate.tile_bytes)}, "
        f"transient {_gib_text(estimate.transient_bytes)}, "
        f"shared matrix cap {_gib_text(estimate.per_microbatch_bytes)}"
    )


_vram_estimate_text = _device_memory_estimate_text


def _resolve_active_matmul_precision(
    setting,
    cached_precision,
    sample,
    workers,
    store,
    sequence_lengths,
):
    """Resolve auto precision across the permitted CUDA execution variants."""
    normalized = normalize_precision_setting(setting)
    execution_mode = normalize_execution_mode(EXECUTION_MODE)
    variants = (
        ("scalar", "tiled")
        if execution_mode == "auto"
        else (execution_mode,)
    )
    if cached_precision is not None:
        print(f"[Precision] Reusing established {cached_precision} results.")
        return cached_precision
    if normalized == "float32":
        return "ieee_fp32"

    candidates = Hardware_Utils.get_available_devices()
    cuda_candidate = _precision_device(candidates)
    if cuda_candidate is None:
        if normalized == "tf32":
            raise ValueError("TF32 was requested, but no CUDA device is available.")
        return "ieee_fp32"
    if normalized == "tf32":
        print("[Precision] TF32 was explicitly selected.")
        return "tf32"

    validation_tasks = list(
        sample[: min(int(ACCELERATOR_CONFIRM_PAIRS), len(sample))]
    )
    if len(validation_tasks) < 2:
        return "ieee_fp32"
    Hardware_Utils.release_device_cache(cuda_candidate)
    memory_plan = accelerator_memory_plan(cuda_candidate.device, lanes=1)
    memory_info = (memory_plan.free_bytes, memory_plan.total_bytes)
    preflight = {
        variant: estimate_accelerator_working_set(
            validation_tasks,
            store=store,
            lengths=sequence_lengths,
            device=cuda_candidate.device,
            lanes=1,
            variant=variant,
            memory_info=memory_info,
        )
        for variant in variants
    }
    for variant, estimate in preflight.items():
        print(
            f"[Precision] Device-memory preflight {variant}: "
            f"{_vram_estimate_text(estimate)}; {estimate.reason}."
        )
    infeasible = [
        f"{variant}: {estimate.reason}"
        for variant, estimate in preflight.items()
        if not estimate.feasible
    ]
    if infeasible:
        print(
            f"[Precision] Selected-plan validation is not device-memory-safe "
            f"({'; '.join(infeasible)}); using IEEE FP32."
        )
        return "ieee_fp32"
    print(
        f"[Precision] Testing FP32/TF32 with "
        f"{', '.join(variants)} CUDA execution on "
        f"{len(validation_tasks)} production-ordered pairs..."
    )

    def run_variant(variant, precision, tasks):
        if variant == "scalar":
            return _run_accelerated_pipeline(
                tasks,
                workers,
                store.path,
                cuda_candidate.device,
                0,
                accelerator_workers=1,
                show_progress=False,
                matmul_precision=precision,
            )
        return run_tiled_accelerator_pipeline(
            tasks,
            store=store,
            lengths=sequence_lengths,
            device=cuda_candidate.device,
            workers=workers,
            lanes=1,
            alignment_callback=calculate_alignment_data,
            alignment_chunk_callback=calculate_alignment_chunk,
            precision=precision,
        )

    try:
        for variant in variants:
            run_variant(variant, "float32", validation_tasks[:2])

        results_by_plan = {}
        rates = {}
        print("Plan       Precision   Throughput (pairs/s)")
        for variant in variants:
            for precision in ("float32", "tf32"):
                started = time.perf_counter()
                results_by_plan[(variant, precision)] = run_variant(
                    variant,
                    precision,
                    validation_tasks,
                )
                elapsed = max(time.perf_counter() - started, 1e-9)
                rates[(variant, precision)] = len(validation_tasks) / elapsed
                print(
                    f"{variant:10} {precision:9} "
                    f"{rates[(variant, precision)]:>20.2f}"
                )
    except Exception as error:
        print(
            f"[Precision] TF32 validation unavailable "
            f"({type(error).__name__}: {error}); using IEEE FP32."
        )
        return "ieee_fp32"

    validation = {}
    for variant in variants:
        validation[variant] = compare_precision_results(
            results_by_plan[(variant, "float32")],
            results_by_plan[(variant, "tf32")],
        )

    fp32_best = max(rates[(variant, "float32")] for variant in variants)
    tf32_best = max(rates[(variant, "tf32")] for variant in variants)
    speedup = tf32_best / max(fp32_best, 1e-9)
    all_equivalent = all(equivalent for equivalent, _reason in validation.values())
    if all_equivalent and speedup >= 1.10:
        print(
            f"[Precision] TF32 passed {', '.join(variants)} numerical validation "
            f"and its best plan was {speedup:.2f}x faster."
        )
        return "tf32"

    if not all_equivalent:
        failed = next(
            f"{variant}: {reason}"
            for variant, (equivalent, reason) in validation.items()
            if not equivalent
        )
        speed_reason = f"numerical validation failed for {failed}"
    else:
        speed_reason = f"best-plan speedup {speedup:.2f}x is below 1.10x"
    print(f"[Precision] Using IEEE FP32: {speed_reason}.")
    return "ieee_fp32"


def _benchmark_processing_plans(
    batch_tasks,
    workers,
    input_h5,
    batch_id,
    embedding_store=None,
    sequence_lengths=None,
    matmul_precision=None,
):
    """Compare the complete CPU path with every accelerator/lane plan."""
    execution_mode = normalize_execution_mode(EXECUTION_MODE)
    candidates = Hardware_Utils.get_available_devices()
    if matmul_precision is None:
        matmul_precision = active_matmul_precision
    if matmul_precision == "tf32":
        candidates = [candidate for candidate in candidates if candidate.backend == "cuda"]
        if not candidates:
            raise RuntimeError("TF32 execution requires an available CUDA device.")
    manual = Hardware_Utils.resolve_device_selection(
        DEVICE_SELECTION, candidates
    )
    if execution_mode == "tiled":
        if manual is not None and not _execution_variants(manual):
            raise ValueError(
                "Tiled execution requires a stream-capable CUDA/ROCm or XPU "
                "accelerator; the selected device "
                f"is '{manual.spec}'."
            )
        candidates = [
            candidate for candidate in candidates
            if _execution_variants(candidate) == ["tiled"]
        ]
        if not candidates:
            raise ValueError(
                "Tiled execution was requested, but no compatible CUDA/ROCm "
                "or XPU accelerator is available."
            )
    if manual is not None and manual.is_cpu:
        print(f"[Hardware] Using manually selected {manual.display_name}.")
        return [Hardware_Utils.BenchmarkResult(manual, 0.0, variant="scalar")]

    sample = list(
        batch_tasks[
            : max(
                2,
                min(int(ACCELERATOR_TUNE_PAIRS), len(batch_tasks)),
            )
        ]
    )
    confirmation_sample = list(
        batch_tasks[
            : max(
                len(sample),
                min(int(ACCELERATOR_CONFIRM_PAIRS), len(batch_tasks)),
            )
        ]
    )

    def execute_plan(
        candidate, variant, lanes, tasks, execution_plan=None
    ):
        if candidate.is_cpu:
            return process_cpu_tasks(
                tasks,
                workers,
                input_h5,
                batch_id,
                show_progress=False,
            )
        if variant == "tiled":
            return run_tiled_accelerator_pipeline(
                tasks,
                store=embedding_store,
                lengths=sequence_lengths,
                device=candidate.device,
                workers=workers,
                lanes=lanes,
                alignment_callback=calculate_alignment_data,
                alignment_chunk_callback=calculate_alignment_chunk,
                precision=matmul_precision,
                execution_plan=execution_plan,
                print_summary=False,
            )
        return _run_accelerated_pipeline(
            tasks,
            workers,
            input_h5,
            candidate.device,
            batch_id,
            accelerator_workers=lanes,
            show_progress=False,
            matmul_precision=matmul_precision,
        )

    if manual is not None:
        candidates = [manual]
        print(
            f"[Hardware] Benchmarking plans on manually selected "
            f"{manual.display_name}."
        )

    print(
        f"[Hardware] Benchmarking {len(candidates)} device(s) with "
        f"{len(sample)} production-ordered alignment pairs..."
    )
    print(
        "Device/backend                 Plan      Lanes   Memory peak/safe "
        "Throughput (pairs/s)   Status"
    )
    results = []
    for candidate in candidates:
        candidate_results = []
        candidate_memory_info = None
        base_memory_plan = None
        tiled_preflight_error = None
        if (
            candidate.backend in {"cuda", "xpu"}
            and embedding_store is not None
            and sequence_lengths is not None
        ):
            Hardware_Utils.release_device_cache(candidate)
            try:
                base_memory_plan = accelerator_memory_plan(
                    candidate.device, lanes=1
                )
                candidate_memory_info = (
                    base_memory_plan.free_bytes,
                    base_memory_plan.total_bytes,
                )
            except (RuntimeError, NotImplementedError) as error:
                tiled_preflight_error = (
                    f"device-memory information unavailable: {error}"
                )
        lane_candidates = (
            [1]
            if candidate.is_cpu
            else _accelerator_lane_candidates(candidate.device, workers)
        )
        variants = _execution_variants(candidate)
        if "tiled" in variants and (
            embedding_store is None or sequence_lengths is None
        ):
            variants.remove("tiled")
        if "tiled" in variants and tiled_preflight_error is not None:
            variants.remove("tiled")
            print(
                f"{candidate.display_name}: tiled plan skipped; "
                f"{tiled_preflight_error}."
            )
        if candidate.is_cpu:
            try:
                process_cpu_tasks(
                    sample[: min(2, len(sample))],
                    workers,
                    input_h5,
                    batch_id,
                    show_progress=False,
                )
            except Exception:
                pass
        else:
            for variant in variants:
                warmup_tasks = sample[: min(2, len(sample))]
                if candidate_memory_info is not None:
                    warmup_estimate = estimate_accelerator_working_set(
                        warmup_tasks,
                        store=embedding_store,
                        lengths=sequence_lengths,
                        device=candidate.device,
                        lanes=1,
                        variant=variant,
                        memory_info=candidate_memory_info,
                    )
                    if not warmup_estimate.feasible:
                        continue
                try:
                    execute_plan(candidate, variant, 1, warmup_tasks)
                except Exception:
                    pass

        if "tiled" in variants and isinstance(
            base_memory_plan, AcceleratorMemoryPlan
        ):
            print(
                f"[Hardware] Staged tiled tuning on "
                f"{candidate.display_name}: lanes, packet cap, CPU workers, "
                f"CPU chunk, then scorer."
            )

            def memory_plan_factory(lanes):
                return accelerator_memory_plan(
                    candidate.device,
                    lanes=lanes,
                    memory_info=candidate_memory_info,
                )

            def measure_tiled_plan(execution_plan, plan_tasks):
                with TiledAcceleratorSession(
                    store=embedding_store,
                    lengths=sequence_lengths,
                    device=candidate.device,
                    workers=workers,
                    lanes=execution_plan.lanes,
                    alignment_callback=calculate_alignment_data,
                    alignment_chunk_callback=calculate_alignment_chunk,
                    precision=matmul_precision,
                    memory_plan_override=memory_plan_factory(
                        execution_plan.lanes
                    ),
                    execution_plan=execution_plan,
                    print_summary=False,
                ) as tuning_session:
                    plan_results, rate, measured_pairs = (
                        measure_accelerator_session(
                            tuning_session, plan_tasks
                        )
                    )
                    plan_metrics = tuning_session.metrics()
                return {
                    "rate": rate,
                    "measured_pairs": measured_pairs,
                    "peak_memory_bytes": plan_metrics[
                        "peak_allocated_bytes"
                    ],
                    "compilation_seconds": plan_metrics[
                        "compilation_seconds"
                    ],
                    "results": plan_results,
                }

            tiled_ranked, tiled_observations = (
                benchmark_accelerator_execution_plans(
                    lane_candidates=lane_candidates,
                    memory_plan_factory=memory_plan_factory,
                    workers=workers,
                    short_tasks=sample,
                    confirmation_tasks=confirmation_sample,
                    remaining_pairs=len(batch_tasks),
                    measure=measure_tiled_plan,
                    allow_compilation=True,
                    allow_graph_compilation=is_nvidia_cuda(
                        candidate.device
                    ),
                )
            )
            for observation in tiled_observations:
                plan = observation.execution_plan
                cap_mib = plan.microbatch_workspace_bytes / (1024 ** 2)
                status = (
                    f"{observation.pairs_per_second:.2f} pairs/s"
                    if observation.succeeded
                    else observation.error
                )
                print(
                    f"  tiled lanes={plan.lanes}, cap={cap_mib:.0f} MiB, "
                    f"workers={plan.active_cpu_workers}, "
                    f"chunk={plan.cpu_chunk_size}, "
                    f"{plan.scorer_variant}: {status}"
                )
            for observation in tiled_ranked:
                candidate_results.append(
                    Hardware_Utils.BenchmarkResult(
                        candidate,
                        observation.pairs_per_second,
                        lanes=observation.execution_plan.lanes,
                        variant="tiled",
                        execution_plan=observation.execution_plan,
                        peak_memory_bytes=observation.peak_memory_bytes,
                    )
                )

        staged_tiled = isinstance(base_memory_plan, AcceleratorMemoryPlan)
        for variant in (
            variant
            for variant in variants
            if variant != "tiled" or not staged_tiled
        ):
            for lanes in lane_candidates:
                memory_estimate = None
                vram_label = "--"
                if candidate_memory_info is not None:
                    memory_estimate = estimate_accelerator_working_set(
                        sample,
                        store=embedding_store,
                        lengths=sequence_lengths,
                        device=candidate.device,
                        lanes=lanes,
                        variant=variant,
                        memory_info=candidate_memory_info,
                    )
                    vram_label = (
                        f"{memory_estimate.projected_peak_bytes / (1024 ** 3):.1f}/"
                        f"{memory_estimate.safe_peak_bytes / (1024 ** 3):.1f}G"
                    )
                    if not memory_estimate.feasible:
                        result = Hardware_Utils.BenchmarkResult(
                            candidate,
                            None,
                            lanes=lanes,
                            error=(
                                f"Device-memory preflight: "
                                f"{memory_estimate.reason}"
                            ),
                            variant=variant,
                        )
                        print(
                            f"{candidate.display_name[:30]:30}  {variant:8}  "
                            f"{lanes:>5}   {vram_label:>14}   "
                            f"{'--':>20}   skipped: {memory_estimate.reason}"
                        )
                        candidate_results.append(result)
                        continue
                started = time.perf_counter()
                try:
                    execute_plan(candidate, variant, lanes, sample)
                    elapsed = max(time.perf_counter() - started, 1e-9)
                    rate = len(sample) / elapsed
                    result = Hardware_Utils.BenchmarkResult(
                        candidate,
                        rate,
                        lanes=lanes,
                        variant=variant,
                    )
                    print(
                        f"{candidate.display_name[:30]:30}  {variant:8}  "
                        f"{lanes:>5}   {vram_label:>14}   "
                        f"{rate:>20.2f}   ok"
                    )
                except Exception as error:
                    result = Hardware_Utils.BenchmarkResult(
                        candidate,
                        None,
                        lanes=lanes,
                        error=f"{type(error).__name__}: {error}",
                        variant=variant,
                    )
                    print(
                        f"{candidate.display_name[:30]:30}  {variant:8}  "
                        f"{lanes:>5}   {vram_label:>14}   "
                        f"{'--':>20}   {result.error}"
                    )
                candidate_results.append(result)

        selected_short = []
        for variant in variants:
            successful = [
                result
                for result in candidate_results
                if result.variant == variant and result.succeeded
            ]
            if not successful:
                continue
            fastest_rate = max(float(result.value) for result in successful)
            selected_short.append(
                min(
                    (
                        result
                        for result in successful
                        if float(result.value) >= fastest_rate * 0.97
                    ),
                    key=lambda result: result.lanes,
                )
            )

        if (
            candidate.backend in {"cuda", "xpu"}
            and len(confirmation_sample) > len(sample)
        ):
            print(
                f"[Hardware] Confirming {candidate.display_name} plans on "
                f"{len(confirmation_sample)} production-ordered pairs..."
            )
            for short_result in selected_short:
                if (
                    short_result.variant == "tiled"
                    and short_result.execution_plan is not None
                ):
                    # The staged tuner already confirmed its two finalists on
                    # this production-ordered sample.
                    results.append(short_result)
                    continue
                memory_estimate = estimate_accelerator_working_set(
                    confirmation_sample,
                    store=embedding_store,
                    lengths=sequence_lengths,
                    device=candidate.device,
                    lanes=short_result.lanes,
                    variant=short_result.variant,
                    memory_info=candidate_memory_info,
                )
                print(
                    f"  [Device memory] {short_result.variant}, "
                    f"lanes={short_result.lanes}: "
                    f"{_vram_estimate_text(memory_estimate)}; "
                    f"{memory_estimate.reason}."
                )
                if not memory_estimate.feasible:
                    print(
                        f"  {short_result.variant:8} lanes="
                        f"{short_result.lanes:<2} --   skipped by "
                        f"device-memory preflight"
                    )
                    continue
                started = time.perf_counter()
                try:
                    execute_plan(
                        candidate,
                        short_result.variant,
                        short_result.lanes,
                        confirmation_sample,
                        short_result.execution_plan,
                    )
                    elapsed = max(time.perf_counter() - started, 1e-9)
                    rate = len(confirmation_sample) / elapsed
                    confirmed = Hardware_Utils.BenchmarkResult(
                        candidate,
                        rate,
                        lanes=short_result.lanes,
                        variant=short_result.variant,
                        execution_plan=short_result.execution_plan,
                        peak_memory_bytes=short_result.peak_memory_bytes,
                    )
                    print(
                        f"  {short_result.variant:8} lanes="
                        f"{short_result.lanes:<2} {rate:.2f} pairs/s   ok"
                    )
                    results.append(confirmed)
                except Exception as error:
                    print(
                        f"  {short_result.variant:8} lanes="
                        f"{short_result.lanes:<2} --   "
                        f"{type(error).__name__}: {error}"
                    )
        else:
            results.extend(selected_short)
        Hardware_Utils.release_device_cache(candidate)

    ranked = Hardware_Utils.rank_benchmark_results(
        results, higher_is_better=True
    )
    if not ranked:
        raise RuntimeError("No CPU or accelerator alignment plan completed.")
    winner = ranked[0]
    fastest = max(
        (result for result in results if result.succeeded),
        key=lambda result: float(result.value),
    )
    tie_applied = (
        winner.candidate.spec != fastest.candidate.spec
        or winner.lanes != fastest.lanes
        or winner.variant != fastest.variant
    )
    print(
        f"[Hardware] Selected {winner.candidate.display_name} with "
        f"{winner.variant} plan and {winner.lanes} lane(s); 3% tie preference "
        f"{'applied' if tie_applied else 'not applied'}."
    )
    return ranked


def _calculate_result_chunk_with_ranked_plans(
    tasks,
    ranked_plans,
    active_plan_index,
    *,
    workers,
    input_h5,
    embedding_store,
    sequence_lengths,
    matmul_precision,
    tiled_sessions,
):
    """Calculate one bounded write chunk without creating a batch file."""

    while active_plan_index < len(ranked_plans):
        plan = ranked_plans[active_plan_index]
        session_key = None
        session = None
        try:
            if plan.candidate.is_cpu:
                results = process_cpu_tasks(
                    tasks,
                    workers,
                    input_h5,
                    -1,
                    show_progress=False,
                )
            elif plan.variant == "tiled":
                session_key = (
                    plan.candidate.spec,
                    int(plan.lanes),
                    str(matmul_precision),
                    plan.execution_plan,
                )
                session = tiled_sessions.get(session_key)
                if session is None:
                    session = TiledAcceleratorSession(
                        store=embedding_store,
                        lengths=sequence_lengths,
                        device=plan.candidate.device,
                        workers=workers,
                        lanes=plan.lanes,
                        alignment_callback=calculate_alignment_data,
                        alignment_chunk_callback=calculate_alignment_chunk,
                        precision=matmul_precision,
                        execution_plan=plan.execution_plan,
                    )
                    tiled_sessions[session_key] = session
                backend = get_accelerator_backend(plan.candidate.device)
                for attempt in range(4):
                    try:
                        streamed = session.run_pair_stream(
                            (
                                (ordinal, task[0], task[1])
                                for ordinal, task in enumerate(tasks)
                            ),
                            chunk_size=max(1, len(tasks)),
                        )
                        results = [tuple(result[1:]) for result in streamed]
                        break
                    except Exception as error:
                        if not backend.is_out_of_memory(error) or attempt == 3:
                            raise
                        session.recover_from_oom(
                            minimum_budget=16 * 1024 * 1024
                        )
                else:
                    raise RuntimeError("Accelerator OOM recovery did not complete.")
            else:
                results = process_accelerated_tasks(
                    tasks,
                    workers,
                    input_h5,
                    plan.candidate.device,
                    -1,
                    accelerator_workers=plan.lanes,
                    embedding_store=embedding_store,
                    sequence_lengths=sequence_lengths,
                    matmul_precision=matmul_precision,
                    execution_variant=plan.variant,
                    show_progress=False,
                )
            if len(results) != len(tasks):
                raise RuntimeError(
                    f"Alignment plan produced {len(results)} results for "
                    f"{len(tasks)} requested pairs."
                )
            return results, active_plan_index
        except (RuntimeError, NotImplementedError, MemoryError) as error:
            if session_key is not None and session is not None:
                session.close()
                tiled_sessions.pop(session_key, None)
            if Hardware_Utils.normalize_device_selection(DEVICE_SELECTION) != "auto":
                raise RuntimeError(
                    f"Alignment chunk failed on manually selected device "
                    f"'{plan.candidate.spec}': {error}"
                ) from error
            active_plan_index += 1
            if active_plan_index >= len(ranked_plans):
                raise RuntimeError(
                    "Every benchmarked alignment processing plan failed."
                ) from error
            fallback = ranked_plans[active_plan_index]
            print(
                f"[Hardware] {type(error).__name__}; retrying uncommitted "
                f"alignment work on {fallback.candidate.display_name}, "
                f"lanes={fallback.lanes}."
            )
    raise RuntimeError("No alignment processing plan is available.")


# %% =======================================
# MAIN
# ==========================================
def _compute_target_selection(
    input_h5,
    safe_headers,
    sequence_lengths,
    embedding_checksum,
):
    n = len(safe_headers)
    total_pairs = n * (n - 1) // 2
    enabled = bool(EDGE_PREFILTERING and float(PREFILTER_STRENGTH) > 0.0)
    if not enabled or n < 2:
        required_mask = np.triu(np.ones((n, n), dtype=bool), k=1)
        cutoff = float("-inf")
        profile = SparsityProfile(
            enabled=False,
            sparsity_percent=0.0,
            total_pair_count=total_pairs,
            keep_count=total_pairs,
            cutoff=cutoff,
            pooling_method=str(POOLING_METHOD),
            length_ratio_power=float(LENGTH_RATIO_POWER),
            selection_fingerprint=make_selection_fingerprint(
                embedding_checksum=embedding_checksum,
                sparsity_percent=0.0,
                keep_count=total_pairs,
                cutoff=cutoff,
                pooling_method=POOLING_METHOD,
                length_ratio_power=LENGTH_RATIO_POWER,
            ),
        )
        return required_mask, profile

    print(
        f"\n--- Edge Prefiltering: calculating {POOLING_METHOD} pooled "
        f"length-adjusted similarities ---"
    )
    pooled_embeddings = []
    with h5py.File(input_h5, "r") as hf:
        for header in tqdm(
            safe_headers, desc=f"Pooling Embeddings ({POOLING_METHOD})"
        ):
            embedding = hf["embeddings"][header][:]
            if POOLING_METHOD == "max":
                pooled = np.max(embedding, axis=0)
            else:
                pooled = np.mean(embedding, axis=0)
            pooled_embeddings.append(pooled)
    pooled_embeddings = np.asarray(pooled_embeddings, dtype=np.float32)
    norms = np.linalg.norm(pooled_embeddings, axis=1, keepdims=True)
    normalized = pooled_embeddings / np.where(norms == 0, 1e-8, norms)
    adjusted_scores = np.clip(
        np.dot(normalized, normalized.T), -1.0, 1.0
    ).astype(np.float32, copy=False)
    lengths = np.asarray(sequence_lengths, dtype=np.int32)
    minimum = np.minimum(lengths[:, None], lengths[None, :])
    maximum = np.maximum(np.maximum(lengths[:, None], lengths[None, :]), 1)
    length_ratio = minimum / maximum
    if float(LENGTH_RATIO_POWER) != 1.0:
        length_ratio = length_ratio ** float(LENGTH_RATIO_POWER)
    adjusted_scores *= length_ratio
    required_mask, profile = build_sparsity_profile(
        adjusted_scores,
        embedding_checksum=embedding_checksum,
        enabled=True,
        sparsity_percent=PREFILTER_STRENGTH,
        pooling_method=POOLING_METHOD,
        length_ratio_power=LENGTH_RATIO_POWER,
    )
    del adjusted_scores, pooled_embeddings, normalized, length_ratio
    print(f"  > Sparsity: {profile.sparsity_percent:g}%")
    print(f"  > Adjusted similarity cutoff: {profile.cutoff:.6f}")
    print(
        f"  > Retaining exactly {profile.keep_count} / {total_pairs} pairs "
        f"({100.0 * profile.keep_count / max(1, total_pairs):.2f}%)"
    )
    print("-----------------------------------------------------------\n")
    return required_mask, profile


def _matching_partial_precision(path, identity, profile, requested_precision):
    partial = path + ".partial"
    if not os.path.exists(partial):
        return None
    try:
        with h5py.File(partial, "r") as hf:
            if (
                str(hf.attrs.get("embedding_checksum", ""))
                != identity.embedding_checksum
                or str(hf.attrs.get("model_name", "")) != identity.model_name
                or str(hf.attrs.get("selection_fingerprint", ""))
                != profile.selection_fingerprint
            ):
                return None
            precision = str(
                hf.attrs.get("matmul_precision", "ieee_fp32")
            ).strip().lower()
            precision = {
                "float32": "ieee_fp32",
                "fp32": "ieee_fp32",
                "ieee": "ieee_fp32",
            }.get(precision, precision)
            if requested_precision is not None and precision != requested_precision:
                return None
            return precision if precision in {"ieee_fp32", "tf32"} else None
    except (OSError, RuntimeError, TypeError, ValueError, KeyError):
        return None


def _first_missing_pairs(required_mask, source_path, headers, limit):
    limit = max(0, int(limit))
    sample = []
    reader = (
        CanonicalAlignmentNetworkReader(source_path, len(headers))
        if source_path is not None
        else None
    )
    iterator = iter_mask_pairs(required_mask)
    try:
        while len(sample) < limit:
            pairs = []
            for _ in range(65536):
                try:
                    pairs.append(next(iterator))
                except StopIteration:
                    break
            if not pairs:
                break
            reused = reader.lookup_many(pairs) if reader is not None else {}
            for position, (left, right) in enumerate(pairs):
                if position not in reused:
                    sample.append((left, right, headers[left], headers[right]))
                    if len(sample) >= limit:
                        break
    finally:
        if reader is not None:
            reader.close()
    return sample


def _next_pair_chunk(iterator, first_pair, chunk_size):
    pairs = [first_pair]
    while len(pairs) < chunk_size:
        try:
            pairs.append(next(iterator))
        except StopIteration:
            return pairs, None
    try:
        return pairs, next(iterator)
    except StopIteration:
        return pairs, None


def run_job_distributor():
    global active_matmul_precision, active_embedding_store
    global active_sequence_lengths, FINAL_OUTPUT_NET
    try:
        normalize_execution_mode(EXECUTION_MODE)
        precision_setting = normalize_precision_setting(ACCELERATOR_PRECISION)
        configure_runtime_paths()
    except ValueError as error:
        print(f"\n❌ Cannot start alignment:\n{error}")
        return

    try:
        set_start_method("spawn")
    except RuntimeError:
        pass

    print(f"Loading metadata from {FULL_INPUT_HDF5}...")
    if not os.path.exists(FULL_INPUT_HDF5):
        print("Embeddings file not found.")
        return
    try:
        headers, safe_headers, seq_lens, manifest = load_embedding_metadata(
            FULL_INPUT_HDF5
        )
    except EmbeddingFileError as error:
        print(f"\n❌ Cannot start alignment:\n{error}")
        return

    print("Calculating checksum of input embedding file...")
    current_checksum = calculate_file_hash(FULL_INPUT_HDF5)
    print(f"  > Checksum: {current_checksum}")
    required_mask, sparsity_profile = _compute_target_selection(
        FULL_INPUT_HDF5,
        safe_headers,
        seq_lens,
        current_checksum,
    )
    identity = AlignmentNetworkIdentity(
        headers=tuple(headers),
        sequence_lengths=tuple(int(value) for value in seq_lens),
        embedding_checksum=current_checksum,
        model_name=manifest.model_name,
        gap_penalties=(float(LOCAL_GAP_P), float(GLOBAL_GAP_P)),
        saving_mode=manifest.saving_mode,
    )
    requested_precision = {
        "float32": "ieee_fp32",
        "tf32": "tf32",
    }.get(precision_setting)

    if (
        not sparsity_profile.enabled
        and os.path.exists(FINAL_OUTPUT_NET)
        and not completed_target_matches(
            FINAL_OUTPUT_NET,
            identity=identity,
            sparsity_profile=sparsity_profile,
            matmul_precision=requested_precision,
            target_mask=required_mask,
        )
    ):
        stem, extension = os.path.splitext(FINAL_OUTPUT_NET)
        FINAL_OUTPUT_NET = f"{stem}_dense{extension}"

    if os.path.exists(FINAL_OUTPUT_NET):
        if completed_target_matches(
            FINAL_OUTPUT_NET,
            identity=identity,
            sparsity_profile=sparsity_profile,
            matmul_precision=requested_precision,
            target_mask=required_mask,
        ):
            print(f"✅ Requested network is already complete: {FINAL_OUTPUT_NET}")
            return
        backup = backup_incompatible_target(FINAL_OUTPUT_NET)
        print(f"[Resume] Preserved incompatible target as: {backup}")

    partial_precision = _matching_partial_precision(
        FINAL_OUTPUT_NET,
        identity,
        sparsity_profile,
        requested_precision,
    )
    discovery_precision = partial_precision or requested_precision
    diagnostics = []
    candidates = discover_compatible_alignment_networks(
        NETWORK_DIR,
        identity=identity,
        target_mask=required_mask,
        active_target=FINAL_OUTPUT_NET,
        required_precision=discovery_precision,
        diagnostics=diagnostics,
    )
    source = next(
        (candidate for candidate in candidates if candidate.reusable_edge_count > 0),
        None,
    )
    established_precision = partial_precision or (
        source.matmul_precision if source is not None else None
    )
    if source is not None:
        print(
            f"[Reuse] Selected {os.path.basename(source.path)}: "
            f"{source.reusable_edge_count:,} / "
            f"{sparsity_profile.keep_count:,} target edges reusable."
        )
    else:
        print("[Reuse] No compatible network contains requested target edges.")

    missing_without_partial = sparsity_profile.keep_count - (
        source.reusable_edge_count if source is not None else 0
    )
    benchmark_tasks = []
    ranked_plans = []
    active_plan_index = 0
    tiled_sessions = {}
    source_reader = None
    writer = None
    pbar = None
    try:
        if established_precision is None and missing_without_partial == 0:
            established_precision = requested_precision or "ieee_fp32"

        if established_precision is None:
            benchmark_tasks = _first_missing_pairs(
                required_mask,
                None if source is None else source.path,
                safe_headers,
                ACCELERATOR_CONFIRM_PAIRS,
            )
            active_embedding_store = EmbeddingTileStore(
                FULL_INPUT_HDF5, safe_headers, HOST_CACHE_GB
            )
            active_sequence_lengths = list(seq_lens)
            active_matmul_precision = _resolve_active_matmul_precision(
                precision_setting,
                None,
                benchmark_tasks,
                WORKERS,
                active_embedding_store,
                active_sequence_lengths,
            )
        else:
            active_matmul_precision = established_precision

        writer = ResumableAlignmentNetworkWriter(
            FINAL_OUTPUT_NET,
            identity=identity,
            sparsity_profile=sparsity_profile,
            matmul_precision=active_matmul_precision,
        )
        remaining = sparsity_profile.keep_count - writer.committed_count
        if remaining == 0:
            writer.finalize()
            writer = None
            print(f"✅ Published resumed network: {FINAL_OUTPUT_NET}")
            return

        calculation_may_be_needed = missing_without_partial > 0
        if calculation_may_be_needed:
            _validate_execution_mode_hardware()
            if active_matmul_precision == "tf32" and _precision_device(
                Hardware_Utils.get_available_devices()
            ) is None:
                raise ValueError(
                    "Compatible TF32 edges were found, but missing TF32 edges "
                    "require an eligible NVIDIA CUDA device."
                )
            if active_embedding_store is None:
                active_embedding_store = EmbeddingTileStore(
                    FULL_INPUT_HDF5, safe_headers, HOST_CACHE_GB
                )
                active_sequence_lengths = list(seq_lens)
            if not benchmark_tasks:
                benchmark_tasks = _first_missing_pairs(
                    required_mask,
                    None if source is None else source.path,
                    safe_headers,
                    ACCELERATOR_CONFIRM_PAIRS,
                )
            if benchmark_tasks:
                ranked_plans = _benchmark_processing_plans(
                    benchmark_tasks,
                    WORKERS,
                    FULL_INPUT_HDF5,
                    -1,
                    embedding_store=active_embedding_store,
                    sequence_lengths=active_sequence_lengths,
                    matmul_precision=active_matmul_precision,
                )

        if source is not None:
            source_reader = CanonicalAlignmentNetworkReader(
                source.path, len(headers)
            )

        pair_iterator = iter_mask_pairs(
            required_mask,
            start_i=writer.next_i,
            start_j=writer.next_j,
        )
        first_pair = next(pair_iterator, None)
        reused_total = 0
        calculated_total = 0
        pbar = tqdm(
            total=sparsity_profile.keep_count,
            initial=writer.committed_count,
            desc="Alignment Network",
            unit="edge",
        )
        while first_pair is not None:
            pairs, following_pair = _next_pair_chunk(
                pair_iterator, first_pair, 65_536
            )
            reused = (
                source_reader.lookup_many(pairs)
                if source_reader is not None
                else {}
            )
            missing_positions = [
                position for position in range(len(pairs)) if position not in reused
            ]
            calculated = {}
            if missing_positions:
                if not ranked_plans:
                    raise RuntimeError(
                        "The selected compatible network does not cover the "
                        "target, but no calculation plan is available."
                    )
                tasks = CompactPairTasks(len(missing_positions), safe_headers)
                for position in missing_positions:
                    tasks.append(*pairs[position])
                chunk_results, active_plan_index = (
                    _calculate_result_chunk_with_ranked_plans(
                        tasks,
                        ranked_plans,
                        active_plan_index,
                        workers=WORKERS,
                        input_h5=FULL_INPUT_HDF5,
                        embedding_store=active_embedding_store,
                        sequence_lengths=active_sequence_lengths,
                        matmul_precision=active_matmul_precision,
                        tiled_sessions=tiled_sessions,
                    )
                )
                by_pair = {
                    (int(result[0]), int(result[1])): result
                    for result in chunk_results
                }
                for position in missing_positions:
                    calculated[position] = by_pair[pairs[position]]
            records = [
                reused[position] if position in reused else calculated[position]
                for position in range(len(pairs))
            ]
            writer.commit(
                records,
                next_pair=following_pair if following_pair is not None else (len(headers), len(headers)),
            )
            reused_total += len(reused)
            calculated_total += len(missing_positions)
            pbar.update(len(pairs))
            pbar.set_postfix(
                reused=f"{reused_total:,}",
                calculated=f"{calculated_total:,}",
                committed=f"{writer.committed_count:,}",
                refresh=False,
            )
            first_pair = following_pair

        writer.finalize()
        writer = None
        print(
            f"✅ Published {FINAL_OUTPUT_NET}: {reused_total:,} reused, "
            f"{calculated_total:,} calculated this run."
        )
    except (ValueError, RuntimeError, NotImplementedError, MemoryError) as error:
        print(f"\n❌ Alignment network was not published:\n{error}")
        raise
    finally:
        if pbar is not None:
            pbar.close()
        if source_reader is not None:
            source_reader.close()
        if writer is not None:
            writer.close()
        for session in tiled_sessions.values():
            session.close()
        active_embedding_store = None
        active_sequence_lengths = None

def main(argv=None):
    load_tool_settings(globals(), __file__, PROJECT_ROOT, argv)
    run_job_distributor()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
